### ISSUE TITLE
running merqury.sh, error is "merqury-1.3/eval/spectra-cn.sh: line 24: meryl: command not found"

### ISSUE THREAD

**Issue by zhaoyuhe-zyh** [marbl/merqury#100]
when i running merqury.sh script, the xxx.spectra.cn.log was like:
03.Software/merqury/merqury-1.3/eval/spectra-cn.sh: line 24: meryl: command not found
ModuleCmd_Load.c(204):ERROR:105: Unable to locate a modulefile for 'R'
03.Software/merqury/merqury-1.3/build/filt.sh: line 16: meryl: command not found
Processing file Lycoris-all.hist
Running time : 0 h 0 m 0 sec

03.Software/merqury/merqury-1.3/build/filt.sh: line 33: meryl: command not found
03.Software/merqury/merqury-1.3/eval/spectra-cn.sh: line 64: meryl: command not found
03.Software/merqury/merqury-1.3/eval/spectra-cn.sh: line 81: meryl: command not found
03.Software/merqury/merqury-1.3/eval/spectra-cn.sh: line 82: meryl: command not found
03.Software/merqury/merqury-1.3/eval/spectra-cn.sh: line 88: meryl: command not found
03.Software/merqury/merqury-1.3/eval/spectra-cn.sh: line 89: meryl: co
Copy = 2 ..

Copy = 3 ..

Copy = 4 ..

Copy >4 ..

# Copy numbers in k-mers found only in asm
No asm2_fa given. Done.
# Lyco-genome only
# Write output
# Get asm only for spectra-asm
#	Plot out1.spectra-asm.hist
  Rscript 03.Software/merqury/merqury-1.3/plot/plot_spectra_cn.R -f out1.spectra-asm.hist -o out1.spectra-asm -z out1.dist_only.hist

# Clean up
Done!
tory
03.Software/merqury/merqury-1.3/eval/spectra-cn.sh: line 88: meryl: command not found
03.Software/merqury/merqury-1.3/eval/spectra-cn.sh: line 89: meryl: command not found
rm: cannot remove ‘read.k.Lyco-genome.3.meryl’: No such file or directory
03.Software/merqury/merqury-1.3/eval/spectra-cn.sh: line 88: meryl: command not found
03.Software/merqury/merqury-1.3/eval/spectra-cn.sh: line 89: meryl: command not found
rm: cannot remove ‘read.k.Lyco-genome.4.meryl’: No such file or directory
03.Software/merqury/merqury-1.3/eval/spectra-cn.sh: line 95: meryl: command not found
03.Software/merqury/merqury-1.3/eval/spectra-cn.sh: line 96: meryl: command not found

Does anyone know how to solve this?

**Comment by arangrhie** [comment]
Seems like `meryl` is not installed? How did you installed Merqury?

**Comment by arangrhie** [comment]
Please use meryl v1.4.1!
