### ISSUE TITLE
Odd Spectra.asm plot generated 

### ISSUE THREAD

**Issue by ap1438** [marbl/merqury#102]
Hi,

I ran merquery for assembly evaluation in trio mode and got this weird plot. I cannot understand what's wrong in the assembly.

![image](https://user-images.githubusercontent.com/79984931/226623030-bf842875-0359-4b81-b535-51f32ff578f4.png)

I ran the same command for other 2 assemblies and the plots were perfect as shown in the example.

**Comment by arangrhie** [comment]
Hi,
Try re-generating the plots with `-m` `-n` options. More in: https://github.com/marbl/merqury/issues/27.

**Comment by arangrhie** [comment]
It looks like some junk sequence that got into your assembly.
You could try fish out where the low-frequency kmers are present along your two assemblies.
For example,
```
meryl less-than 25 read-db.meryl output lowcov.meryl
meryl intersect lowcov.meryl asm1.meryl output asm1_lowcov.meryl
# in bed format
meryl-lookup -bed -sequence asm1.fasta -mers asm1_lowcov.meryl | bedtools merge -i - > asm1_lowcov.bed
# in wig format
meryl-lookup -wig-count asm1_lowcov.wig
```
And apply the same on asm2.
The .wig file will have values of the multiplicity seen in the low_cov.meryl.
See where most of the low-coverage kmers are present. Fish out some contigs with multiple hits, and try a BLAST search or so. It will show up if it was a contaminant.

**Comment by arangrhie** [comment]
That is because Merqury tries to show the error (dist_only.hist) results by default.
If you aren't interested in it, try generate one without the `-z hifi_S33.dist_only.hist`.
```
Rscript  $MERQURY/plot/plot_spectra_cn.R -m 250 -n 500000 -f hifi_S33.spectra-asm.hist -o check_hifi_33_asm
```

Best,
Arang
