### ISSUE TITLE
could not installed the meryl ,and the thereis no file discovered the compile

### ISSUE THREAD

**Issue by Jiangjiangzhang6** [marbl/merqury#104]
If the binary doesn't work, download the source and compile:

cd meryl/src
make -j 24
export PATH=/path/to/meryl/…/bin:$PATH
![image](https://user-images.githubusercontent.com/101324838/229048535-332f3e1d-919a-4564-86e8-bf86b117a86c.png)
 there is the file that download from the source, but didnot find the src ditionary. how could  get the src folder, and how to install the meryl
thank you my friend

**Comment by brianwalenz** [comment]
I updated the README to include the directions:
```
git clone https://github.com/marbl/meryl
cd meryl/src
make
```
(then add meryl/build/bin/ to your path)

**Comment by arangrhie** [comment]
Feel free to come back if this still does not work, or report to meryl github.
