### ISSUE TITLE
R plot doesn't seem right

### ISSUE THREAD

**Issue by JennyCNS** [marbl/merqury#105]
Hello,

I am running the following script
#estimate best k
sh $MERQURY/best_k.sh 1089729222
#19.9928 so 20

```
# 1. Build meryl dbs
meryl k=20 count fEpiCoi_cnag1_curated_primary.no_mt.fa output hamour-genome-job.meryl threads=9 memory=130

#2. merge output
meryl union-sum ./hamour.meryl output hamour.meryl

$MERQURY/merqury.sh hamour.meryl fEpiCoi_cnag1_curated_primary.no_mt.fa test1
```

when I merge the files together I still have a lot of files in the folder, 
<img width="506" alt="image" src="https://user-images.githubusercontent.com/124353498/235705211-4ffc3393-b28f-4773-b29f-435168a6a6a6.png">

and my plots look like this

![test1 fEpiCoi_cnag1_curated_primary no_mt spectra-cn fl](https://user-images.githubusercontent.com/124353498/235705372-b293e027-ac0f-4f6d-b175-b74e284e1205.png)

Is there any way you can help me with figure out what is wrong with the analysis?

Thank you,

Jennifer

**Comment by arangrhie** [comment]
Hello, in this step:
```
 # 1. Build meryl dbs
```
You need to use the reads (fq or fa) not the assembly.

Also you could skip
```
#2. merge output
meryl union-sum ./hamour.meryl output hamour.meryl
```

If there is only one meryl file to merge :)

Best,
Arang

**Comment by JennyCNS** [comment]
Hi, I am really sorry for being a pain again but should I merge my forward reverse fastq files for the analysis or just trim the adaptors?

Thank you

**Comment by arangrhie** [comment]
The k-mers will be cleaner after adapter trimming.
And yes, merge (union-sum) the fastq files.

**Comment by arangrhie** [comment]
@JennyCNS feel free to re-open if you need more help!
I've noticed meryl v1.4 had an issue in meryl-lookup, so please use v1.4.1 release instead..!!
