### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by JennyCNS** [marbl/merqury#106]
Hello,

I am using v1.4 of both merqury and meryl and I get an error after merging the output files.

the command I run is:

$MERQURY/eval/spectra-cn.sh -c merged.hamour.meryl fEpiCoi_cnag1_curated_primary.no_mt.fa test1

the error I get is:

Can't interpret 'fEpiCoi_cnag1_curated_primary.no_mt.0.meryl': not a meryl command, option, or recognized input file.
/home/jnascime/merqury/eval/spectra-cn.sh: line 118: -: syntax error: operand expected (error token is "-")
No asm2_fa given. Done.
*** Found test1.spectra-asm.hist ***
#       Plot test1.spectra-asm.hist
  Rscript /home/jnascime/merqury/plot/plot_spectra_cn.R -f test1.spectra-asm.hist -o test1.spectra-asm -z test1.dist_only.hist
Loading required package: argparse
Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘argparse’
Loading required package: ggplot2
Loading required package: scales
Error in ArgumentParser(description = "Make spectra-cn plots. Line, filled, and stacked spectra-cn plots will be generated.") :
  could not find function "ArgumentParser"
Execution halted

# Clean up
rm: cannot remove ‘read.k.fEpiCoi_cnag1_curated_primary.no_mt.0.meryl’: No such file or directory
rm: cannot remove ‘read.k.fEpiCoi_cnag1_curated_primary.no_mt.meryl’: No such file or directory
Done!
(merqury) [jnascime@login02(eddie) meryl-output]$ mv fEpiCoi_cnag1_curated_primary.no_mt.0.meryl/ fEpiCoi_cnag1_curated_primary.no_mt.meryl
mv: cannot stat ‘fEpiCoi_cnag1_curated_primary.no_mt.0.meryl/’: No such file or directory

I tried the statistics option

(merqury) [jnascime@login02(eddie) meryl-output]$ meryl statistics merged.hamour.meryl/ | head                           
Found 1 command tree.
Number of 20-mers that are:
  unique             5887771867  (exactly one instance of the kmer is in the input)
  distinct           7677571429  (non-redundant kmer sequences in the input)
  present           53880823950  (...)
  missing         1091834056347  (non-redundant kmer sequences not in the input)

             number of   cumulative   cumulative     presence
              distinct     fraction     fraction   in dataset
frequency        kmers     distinct        total       (1e-6)

I do not really know how to solve the issue! 

Many thanks,  Jenny

**Comment by arangrhie** [comment]
Hi @JennyCNS,

Sorry, somehow I missed this.
Is Merqury the latest version on github? There is no v1.4 release yet :)

Besides, I'd advice not to use homopolymer compressed kmers for evaluating non-compressed genome assemblies.
I made the `-c` option available only for experimental purposes - to check the spectra-cn plots in compressed space.
QV will be generated, however is not reliable.

Best,
Arang

**Comment by arangrhie** [comment]
Closing this for now as well. Please use meryl v1.4.1 release..!
