### ISSUE TITLE
Does calculating the compressed  k-mers have a great impact on the QV value?

### ISSUE THREAD

**Issue by XXH123a** [marbl/merqury#107]
Dear Dr. Arang Rhie,
       I have the genome assembled by three generations of data and the second-generation data used for correction. Does calculating the compressed k-mers have a great impact on the QV value? Is it meaningful to use merqury to evaluate genome at chromosome level?

**Comment by arangrhie** [comment]
Hello,

Compressed kmers violates the error model assumption used in the QV estimates. I wouldn't use that.
Please use the non-compressed kmers to collect the QV on the (non-compressed) assembly.

Thanks,
Arang
