### ISSUE TITLE
Is high heterozygosity autotetraploid suitable?

### ISSUE THREAD

**Issue by jia-wu-feng** [marbl/merqury#108]
We assembled a highly heterozygous autotetraploid genome. And we got 4 haplotypes. 
I mixed the four haplotypes of this tetraploid and used this tool. 
I'm wondering if it's suitable to run the tool this way.

**Comment by arangrhie** [comment]
Hello @jia-wu-feng ,

You may need to extend the X axis to see the 4th peak on the spectra-cn plots.
QV and phasing won't get affected by ploidy.
Feel free to post your spectra-cn plots in case you need more help.

-Arang

**Comment by jia-wu-feng** [comment]
Thanks,
Jia-Wu
