### ISSUE TITLE
even number k-mer size

### ISSUE THREAD

**Issue by hui-liu** [marbl/merqury#110]
Hi,
I got the best k-mer size is 19.7 by best_k.sh, I wonder if it is correct to use the 20-mer as the k-mer size.

Thanks,
Hui

**Comment by arangrhie** [comment]
Hello, take the ceiling number from best_k.sh. This is the minimum size of k, allowing certain collision in the kmer space. You could use larger k with recent, more accurate datasets. It doesn't matter being even or odd.

Best,
Arang
