### ISSUE TITLE
Handling of assembly gaps

### ISSUE THREAD

**Issue by cabbagesofdoom** [marbl/merqury#113]
Hi,
Apologies if I have missed this in the docs/paper, but how does Merqury handle assembly gaps? Are the `N` bases treated just like any other (and thus generate a set of kmers unique to the assembly), or are they excluded/ignored?
Thanks!
Rich

**Comment by brianwalenz** [comment]
They are poison - a kmer cannot include or span an N.  In effect, it is as if the sequence was split at any block of Ns.

**Comment by cabbagesofdoom** [comment]
Thanks!
