### ISSUE TITLE
Trio binning: parents (Illumina) + hybrid (Hi-Fi). How can I check parenthood?

### ISSUE THREAD

**Issue by carolhsb** [marbl/merqury#115]
Hi

Thank you for developing this amazing tool! 

I have trio-binning data of a hybrid fish: Illumina data from mother and father and Hi-Fi data from the hybrid.

I am uncertain about the father's kinship. How could I evaluate the correct parenthood?

Also, I've tried to run meryl/ hapmer.sh and merqury a few times and got weird results. Therefore, I have some doubts:

---> Can I create a meryl db with Hi-Fi data?

---> In the command below, what I should put in the <read-db.meryl> field? The child short-reads?

merqury.sh <read-db.meryl> [<mat.meryl> <pat.meryl>] <asm1.fasta> [asm2.fasta] <out>

Thanks in advance,

Carolina

**Comment by arangrhie** [comment]
Hello Carolina,

Start by creating a meryl db of your child's HiFi read and each parent's Illumina read. The 3 meryl dbs are the input of hapmers.sh. The hapmer plot will show the shared and inherited portions of each kmers. If there are no strong kinship, you'll see a high fraction of child-only fraction and small fraction of the paternal kmers.

merqury.sh assesses the assembly quality. read-db is the child's db used in hapmers.sh. mat.meryl and pat.meryl are the hapmers.meryl, generated with hapmers.sh.

Feel free to post your inherited_hapmers.ln.png plot if you'd like to discuss more.

https://github.com/marbl/merqury/wiki might be helpful as well.

Best,
Arang

**Comment by carolhsb** [comment]
Thank you very much!!!
