### ISSUE TITLE
USE case: long accurate reads

### ISSUE THREAD

**Issue by Axze-rgb** [marbl/merqury#117]
Hello, 

More and more assemblies come based solely on long reads such as PacBio or Nanopore. Nanopore used to be noisy, but it seems they are not anymore and have an accuracy > 99.99%. Could merqury be reliably used with that kind of reads ? I understand with noisy ONT we would get errors with Kmers, but I don't know what could be wrong using accurate long reads. 

would you recommend merqury in this case? It seems KAT works ok with PacBio reads, but I prefer Merqury because your plots are easier to understand for me. 

Cheers

**Comment by arangrhie** [comment]
Hello @Axze-rgb,

It's probably ok to use the ONT kmers for spectra-cn (like KAT) type of analysis. The QV would be slightly inflated though, as a result of platform specific errors observed in the read and in the assembly. Similarly, HiFi assemblies get higher QV when measuring QV from HiFi kmers compared to Illumina kmers. Usually I see decrease of QV of a polished ONT assembly when measuring from ONT kmers.

To put it in other words, 99.99% accuracy is translated as Q40, which means measuring an assembly that is over Q40 would less reliable.

Cheers,
Arang
