### ISSUE TITLE
What are the spectra-asm in case of a single assembly?

### ISSUE THREAD

**Issue by Axze-rgb** [marbl/merqury#119]
Hello, 

I am evaluating a single assembly (so there is a single input fasta), and I have the spectra-asm plots in my output. As shown in the documentation, I understand those plots are used when comparing two assemblies.

> The spectra-asm shows the distinct k-mers shared between col.fasta and cvi.fasta.

 So, in my case, what do they represent? Or should I just ignore them? I don't understand what they could represent.

Thanks!

**Comment by arangrhie** [comment]
It simply shows which kmers you have covered in your assembly. Sort of a visual representation of the completeness, regardless of the copy numbers. Spectra-cn plot will be more useful as it shows the same information with copy numbers.
