### ISSUE TITLE
Non-count Meryl operations don't appear to use all available cores without explicitly set "threads="

### ISSUE THREAD

**Issue by ASLeonard** [marbl/merqury#12]
Hi,

On the LSF cluster I am using, I've noticed that the Meryl "count" operation behaves as described with respect to the parallelisation section in the README, i.e. using all available cores.
```
export OMP_NUM_THREADS=T; meryl count threads=T ...
```
behaves the same as 
```
export OMP_NUM_THREADS=T; meryl count ...
```
On the other hand, this doesn't appear to be true for other operations (I've only checked intersect and difference), where
```
export OMP_NUM_THREADS=T; meryl difference threads=T ...
```
will run with correct threading while
```
export OMP_NUM_THREADS=T; meryl difference ...
```
will run with only a single core.

I couldn't find much information if these other operations can be safely parallelised, but they appear to give equal output after some manual checking. I was able to run the _eval/spectra-cn.sh_ sequence much faster after manually adding "threads=T" to the many intersection/difference calls.

I wasn't sure if this is some system based issue of SLURM vs LSF, some race condition risk, or if you had any other thoughts on this.

Thanks,
Alex

**Comment by arangrhie** [comment]
Hi Alex, are you using `meryl v1.0`?
There has been few updates to `meryl`, which the latest is (unfortunately) no longer uses system's maximum num. of threads by default in non-counting operations. @brianwalenz can answer more.

Thanks,
Arang

**Comment by ASLeonard** [comment]
Hi Arang,
I am using the master branch tip (https://github.com/marbl/meryl/commit/600f40770b380ff476bd844b35957e4e19f3e592), so that sounds like the reason. It mostly seems to impact the _submit scripts as setting the number of cpus in those scripts via sbatch/bsub/etc doesn't get passed on appropriately to the respective eval or trio scripts.

**Comment by arangrhie** [comment]
Please use the `meryl v1.0` release version as Merqury is optimized on that version.
Phase block part and blobs will fail as the `meryl-lookup` syntax has changed.
Spectra-cn and spectra-asm results are not affected.

**Comment by ASLeonard** [comment]
Hi Arang,
Using `meryl v1.0` does indeed fix the threading issue, now the non-counting operations use the available resources without explicitly setting `threads=T`. I'll stick to that version, thanks for the help.
