### ISSUE TITLE
I don't understand how to get the right K mer size

### ISSUE THREAD

**Issue by Axze-rgb** [marbl/merqury#120]
Hello, I know it seems obvious and easy, but if I use your example with the human genome: 

```
best_k.sh 6.2GB 0.001 
genome: 6.2GB
tolerable collision rate: 0.001
6.2983
```

It's not 21

What am I missing? 

Thanks a lot

**Comment by arangrhie** [comment]
My best_k.sh isn't smart to parse out the `.` and `GB`. Please use `6200000000` for 6.2 GB.

**Comment by Axze-rgb** [comment]
Ahhh, thank you :)
