### ISSUE TITLE
Is there a script to rerun the plot?

### ISSUE THREAD

**Issue by Axze-rgb** [marbl/merqury#121]
Hello, my spectra CN plot cut a peak in the last third. I would like to remake it and give instructions for the x-axis. Is that possible? I mean is there a script I can rerun by changing a number? How do I have to redo the plot in R myself? 
Sorry for the many questions 

Thanks

**Comment by Axze-rgb** [comment]
Yes there is, for the record : 
```Rscript $MERQURY/plot/plot_spectra_cn.R -m 250 -n 2274025 -f H5A2.merqury.hairsplitter_final_assembly.spectra-cn.hist -o H5A2```

This is inside a mamba install of merqury. Thanks

**Comment by Axze-rgb** [comment]
However, I didn't find how to remake the spectra asm?

**Comment by arangrhie** [comment]
Use the `spectra-asm.hist` instead for `-f`

**Comment by Axze-rgb** [comment]
Ah of course, I should have thought of it. Thanks!
