### ISSUE TITLE
Completeness, Switch Error？

### ISSUE THREAD

**Issue by DayTimeMouse** [marbl/merqury#126]
![1716898870793](https://github.com/marbl/merqury/assets/92558135/6994b2ea-8576-4402-8502-fd83774f72d6)

Hi,

What should the completeness in the picture be?
Furthermore, what is the meaning of "all" ? 
Lastly, does the "2" mentioned in the picture refer to a Switch Error?

I used hifi reads to generate hifi.meryl, mat.meryl and pat.meryl are the part of hifi.meryl(used hifi_mat/pat.fastq.gz to generate mat/pat.meryl).

The command:
$MERQURY/merqury.sh hifi.meryl mat.meryl pat.meryl hap1.fasta hap2.fasta phasing

Best regards.

**Comment by DayTimeMouse** [comment]
I used hifi reads to generate read-db.meryl, mat.meryl and pat.meryl are part of read-db.meryl.

**Comment by arangrhie** [comment]
Hello @DayTimeMouse,

Each column represents:

1. Assembly
2. k-mer set used for measuring completeness (all = read set, hap = hap-mers)
3. Solid k-mers found in the assembly
4. Total solid k-mers in the read set
5. Completeness (%)

Please refer to the [wiki page](https://github.com/marbl/merqury/wiki), especially the 3. Phasing part. Looks like your hapmer sets are larger than the read set, which is impossible by definition. The hapmers needs to be computed with parental and child k-mers.
