### ISSUE TITLE
Error in f(...) : Graphics API version mismatch

### ISSUE THREAD

**Issue by ksc289** [marbl/merqury#127]
Hi!! :)
I'm trying to run merqury but I can't obtain all the results. Could you help me please?
I'm following the steps:
# Step  1. Create meryl db:
`/opt/merqury-1.3/meryl count k=21 output /path/to/read-db.meryl /path/to/reads.fastq`

# Step 2. Run merqury:
`/opt/merqury/merqury.sh ./read-db.meryl final_assembly.fa ./merqury_analysis`

I get these results:
`ls -lsa`
total 16528
   4 drwxrwxrwx 6 karen_bioinfo karen_bioinfo    4096 jun  5 13:02 .
   4 drwxrwxr-x 8 karen_bioinfo karen_bioinfo    4096 may 30 10:58 ..
   4 drwxrwxr-x 2 karen_bioinfo karen_bioinfo    4096 jun  5 12:43 logs
   **0 -rw-rw-r-- 1 karen_bioinfo karen_bioinfo       0 jun  5 13:01 merqury_analysis.completeness.stats**
   4 -rw-rw-r-- 1 karen_bioinfo karen_bioinfo      34 jun  5 13:02 merqury_analysis.dist_only.hist
   4 -rw-rw-r-- 1 karen_bioinfo karen_bioinfo      63 jun  5 13:00 merqury_analysis.qv
2168 -rw-rw-r-- 1 karen_bioinfo karen_bioinfo 2217598 jun  5 13:02 merqury_analysis.spectra-asm.hist
   4 -rw-rw-r-- 1 karen_bioinfo karen_bioinfo      19 jun  5 13:00 merqury_analysis.yahs.out_scaffolds_final.only.hist
  32 -rw-rw-r-- 1 karen_bioinfo karen_bioinfo   31196 jun  5 13:01 merqury_analysis.yahs.out_scaffolds_final.qv
 884 -rw-rw-r-- 1 karen_bioinfo karen_bioinfo  897773 jun  5 13:00 merqury_analysis.yahs.out_scaffolds_final.spectra-cn.hist
  12 drwxrwxr-x 2 karen_bioinfo karen_bioinfo   12288 may 30 15:44 meryl_db
   4 -rw-rw-r-- 1 karen_bioinfo karen_bioinfo       2 jun  5 12:43 meryl_db.filt
   4 drwxrwxr-x 2 karen_bioinfo karen_bioinfo    4096 jun  5 12:43 meryl_db.gt0.meryl
   **0 -rw-rw-r-- 1 karen_bioinfo karen_bioinfo       0 jun  5 12:43 meryl_db.hist**
   4 -rw-rw-r-- 1 karen_bioinfo karen_bioinfo      28 jun  5 12:43 meryl_db.hist.ploidy
   0 lrwxrwxrwx 1 karen_bioinfo karen_bioinfo      30 jun  5 12:43 yahs.out_scaffolds_final.fa -> ../yahs.out_scaffolds_final.fa
  12 drwxrwxr-x 2 karen_bioinfo karen_bioinfo   12288 jun  5 12:57 yahs.out_scaffolds_final.meryl
6900 -rw-rw-r-- 1 karen_bioinfo karen_bioinfo 7061688 jun  5 13:01 yahs.out_scaffolds_final_only.bed
6480 -rw-rw-r-- 1 karen_bioinfo karen_bioinfo 6631630 jun  5 13:01 yahs.out_scaffolds_final_only.wig

I'm not getting all the results. Part of the log that the program provides me indicates the following:
PROCESSING TREE #1 using 128 threads.
  opIntersect
    meryl_db
    yahs.out_scaffolds_final.meryl
    output to read.k21.yahs.out_scaffolds_final.meryl

Cleaning up.

Bye.

Found 1 command tree.

Found 1 command tree.

Found 1 command tree.
Loading required package: argparse
Loading required package: ggplot2
Loading required package: scales
Error in f(...) : Graphics API version mismatch
Calls: spectra_cn_plot -> save_plot -> ggsave -> dev -> png_dev -> f
In addition: Warning message:
Using ragg device as default. Ignoring `type` and `antialias` arguments 
Execution halted
rm: cannot remove 'meryl_db.gt.meryl': No such file or directory

Thanks!!

**Comment by arangrhie** [comment]
Hello,

If you installed merqury via conda, that version does not understand .fa.
You could try the latest version in the main branch here (download, set $MERQURY) and re run it in your conda environment, or simply rename your fa to fasta and try again.
I'd recommend to use the latest meryl release + latest version of Merqury on this github repo.
Meryl DBs are compatible, no need to re-generate those.

Thanks,
Arang

**Comment by ksc289** [comment]
Thank you very much for the help. I have reinstalled merqury with conda and meryl (latest versions) and it worked!
Greetings,
Karen
