### ISSUE TITLE
No phase block result

### ISSUE THREAD

**Issue by zhen0506** [marbl/merqury#13]
Hi,
I have been using Merqury to assess a trio-binning assembly. The first three steps successfully completed. However, two phaseblock steps generate files with no data. 
I checked result.phase-block1.log. It indicates "Not enough memory to load 943454956 distinct 21-kmers.
Need at least 4.738 GB memory".
But I assigned 140gb of memory in my slurm script. 
Can you suggest how to resolve the issue.
Thank you.
Zhen

**Comment by fanzhen199156** [comment]
Here is more log.
Enabling 32 threads.
Processing file beauty.hap.p_ctg.fasta
Into beauty.hap.p_ctg.gaps
Total number of 
	Generate haplotype marker sites bed

-- Loading kUsing system JDK.
WARN [2020-09-05T15:55:25,075]  [Globals.java:138] [main]  Development mode is enabled
INFO [2020-09-05T15:55:25,093]  [IgvTools.java:838] [main]  Computing coverage.  File = result.beauty.hap.p_ctg.beauty.bed
Computing coverage.  File = result.beauty.hap.p_ctg.beauty.bed
INFO [2020-09-05T15:55:25,094]  [IgvTools.java:839] [main]  Max zoom = 7
Max zoom = 7
INFO [2020-09-05T15:55:25,096]  [IgvTools.java:840] [main]  Window size = 25
Window size = 25
INFO [2020-09-05T15:55:25,102]  [IgvTools.java:845] [main]  Window functions: mean 
Window functions: mean 
INFO [2020-09-05T15:55:25,103]  [IgvTools.java:846] [main]  Ext factor = 0
Ext factor = 0
INFO [2020-09-05T15:55:25,165]  [DirectoryManager.java:179] [main]  IGV Dir-- Loading kmers from 'F12.meryl' into lookup table.

 p       prefixes             bits gigabytes (allowed: 4 GB)
-- -------------- ---------------- ---------
20        1048576      43466036840     5.060
21        2097152      42589690748     4.958
22        4194304      41780453520     4.864
23        8388608      41105434020     4.785
24       16777216      40698849976     4.738 (smallest)
25       33554432      40829136844     4.753
26       67108864      42033165536     4.893
27      134217728      45384677876     5.283
28      268435456      53031157512     6.174
29      536870912      69267571740     8.064
-- -------------- ---------------- ---------

Not enough memory to load 943454956 distinct 21-kmers.
Need at least 4.738 GB memory.
Processing file result.beauty.hap.p_ctg.sort.bed
Found  and  as haplotypes.
Running time : 0 h 0 m 0 sec

awk: cmd. line:1: fatal: division by zero attempted
Processing file result.beauty.hap.p_ctg.100_20000.phased_block.bed
Num. blocks:	0
Genome covered bases:	0

**Comment by zhen0506** [comment]
I found the reason.
In phase_block.sh, line 52, memory was set to 4 for meryl-lookup.
Please consider modifying it to a larger number.
Thanks,

**Comment by arangrhie** [comment]
Hello Zhen,

That seems to be an impressive amount of hapmers.
Asking out of curiosity. Are you using the [inherited hapmer](https://github.com/marbl/merqury/wiki/1.-Prepare-meryl-dbs#3-build-hap-mer-dbs-for-trios) set?

Arang

**Comment by zhen0506** [comment]
Hi Arang,
Thanks for your reply. I didn't use inherited hapmer in that run. I realized that later and ran it with inherited hapmer. The application finished with no problem.
Thanks,
Zhen
