### ISSUE TITLE
error with finding bedtools and argparse

### ISSUE THREAD

**Issue by olympus-terminal** [marbl/merqury#130]
These tools are installed, but I am getting the error: 

ERROR: Unable to locate a modulefile for 'bedtools'
Loading module 'R/4.2.1'
Loading required package: argparse
Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘argparse’
Loading required package: ggplot2
Loading required package: scales
Error in ArgumentParser(description = "Make block N* or NG* plots. Applicable for scaffolds, contigs, and phased blocks.") : 
  could not find function "ArgumentParser"
Execution halted
Loading required package: argparse
Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘argparse’
Loading required package: ggplot2
Loading required package: scales
Error in ArgumentParser(description = "Make block N* or NG* plots. Applicable for scaffolds, contigs, and phased blocks.") : 
  could not find function "ArgumentParser"
Execution halted

**Comment by arangrhie** [comment]
Duplicate with #131
