### ISSUE TITLE
"no module file for 'bedtools', no package 'argparse'"

### ISSUE THREAD

**Issue by olympus-terminal** [marbl/merqury#131]
I am getting this error, even though bedtools and argparse are installed:

ERROR: Unable to locate a modulefile for 'bedtools'
Loading module 'R/4.2.1'
Loading required package: argparse
Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘argparse’
Loading required package: ggplot2
Loading required package: scales
Error in ArgumentParser(description = "Make block N* or NG* plots. Applicable for scaffolds, contigs, and phased blocks.") : 
  could not find function "ArgumentParser"
Execution halted
Loading required package: argparse
Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘argparse’
Loading required package: ggplot2
Loading required package: scales
Error in ArgumentParser(description = "Make block N* or NG* plots. Applicable for scaffolds, contigs, and phased blocks.") : 
  could not find function "ArgumentParser"
Execution halted

No .png plots are made; most of the other outputs are made successfully.

**Comment by arangrhie** [comment]
Can you try this change [1ad7c32](https://github.com/marbl/merqury/commit/1ad7c328a0098ba7a5edb85a5f6a18fe62869e46)? Seems like you don't have bedtools in your module set up.
