### ISSUE TITLE
meryl-lookup failed (# Per seq QV statistics for haplotype 2)

### ISSUE THREAD

**Issue by theahettasch** [marbl/merqury#132]
Hi!

I have encountered an issue when running the spectra-cn.sh code on two haplotype-separated assemblies. Everything seems to work fine until the "Per seq QV statistics" are calculated for haplotype 2 (maternal) and this error pops up: 

-- Opening input sequences '7411_mat_Bta.fasta'.
-- Opening output file '-'.
wordArray::get()-- eIdx 25217 >= _numValues 24961
meryl-lookup: utility/src/utility/bits-wordArray.H:39: uint128 wordArray::get(uint64): Assertion `eIdx < _numValues' failed.

Failed with 'Aborted'; backtrace (libbacktrace):

Failed with 'Segmentation fault'; backtrace (libbacktrace):

Any suggestions to why this happens? Thank you so much in advance. 

The complete log file is attached below. Note that there there are some errors when plotting the spectra-cn plots as well, but I solved this by running the R-script separately :)

[slurm-trio_1_spectra_cn_14751509.txt](https://github.com/user-attachments/files/15966503/slurm-trio_1_spectra_cn_14751509.txt)

**Comment by arangrhie** [comment]
Hello! Which version of meryl are you using? Could you try with v1.4.1 release if it's not what was used? I think I'd seen this error message in v1.3 release.

**Comment by EdgarMurray-gjf** [comment]
Hi! I was using the conda environment, which includes the v1.3 release. When using v1.4.1 instead I am not getting the error. Thank you!
