### ISSUE TITLE
Options to resize? 

### ISSUE THREAD

**Issue by ghost** [marbl/merqury#133]
Hello, 

my plots are cropped too tightly for my taste, is there a hidden option with the conda install to increase the length of the x axis? for example see this:
![mercury plot hairsplitter_final_assembly spectra-cn st](https://github.com/user-attachments/assets/a6f90a2d-998d-4f26-95ac-fbc66bfcea10)

I would like to go a bit beyond 80. I know it can be done in R, but I didn't find in the program help and maybe it would be more helpful for user? I have installed with conda. 

Thanks

**Comment by arangrhie** [comment]
Hi @Axze-rgb , see https://github.com/marbl/merqury/issues/27 .

**Comment by ghost** [comment]
Perfect
thanks
