### ISSUE TITLE
No plot because ggplot2 deprecation command

### ISSUE THREAD

**Issue by ghost** [marbl/merqury#135]
Hello, 

I have a very strange issue, with my merqury plot being fine, except from some samples, I share the log in attachment but I will post here the strange bits 
[D5C3.merqury.plot.spectra-cn.log](https://github.com/user-attachments/files/16626473/D5C3.merqury.plot.spectra-cn.log)

```
Found 1 command tree.
Loading required package: argparse
Loading required package: ggplot2
Loading required package: scales
Error in `coord_cartesian()`:
! `xlim` must be a vector of length 2, not a number of length 1.
Backtrace:
    ▆
 1. └─global spectra_cn_plot(...)
 2.   └─global plot_line(dat, name, x_max, y_max, zero = dat_0, cutoff = dat_cut)
 3.     └─ggplot2::coord_cartesian(xlim = c(0, x_max), ylim = c(0, y_max))
 4.       └─ggplot2:::check_coord_limits(xlim)
 5.         └─cli::cli_abort(...)
 6.           └─rlang::abort(...)
Warning messages:
1: In max(dat[dat[, 1] != "read-total" & dat[, 1] != "read-only" &  :
  no non-missing arguments to max; returning -Inf
2: The `size` argument of `element_rect()` is deprecated as of ggplot2 3.4.0.
ℹ Please use the `linewidth` argument instead. 
3: A numeric `legend.position` argument in `theme()` was deprecated in ggplot2
3.5.0.
ℹ Please use the `legend.position.inside` argument of `theme()` instead. 
Execution halted

```

and

```
Loading required package: argparse
Loading required package: ggplot2
Loading required package: scales
Error in `[.data.frame`(dat_0, , 3) : undefined columns selected
Calls: spectra_cn_plot -> [ -> [.data.frame
In addition: Warning message:
In max(dat[dat[, 1] != "read-total" & dat[, 1] != "read-only" &  :
  no non-missing arguments to max; returning -Inf
Execution halted
rm: cannot remove 'read.k31.hairsplitter_final_assembly.0.meryl': No such file or directory
rm: cannot remove 'read.k31.hairsplitter_final_assembly.meryl': No such file or directory
```

what is weird is that it seemed to work so far, why suddenly the R command don't? All the required packages are installed. 

Thanks

**Comment by arangrhie** [comment]
Hello @Axze-rgb, can you check your .hist files are properly made?
Seems like you re-ran Merqury in the same directory. If any of the previously made `.hist` was malformed, it could throw weird error messages. I'd recommend to make a clean new directory and start merqury again.

**Comment by ghost** [comment]
doing that right now

**Comment by ghost** [comment]
indeed it worked, thanks a lot for your patience.

**Comment by ghost** [comment]
I am sorry the issue seems somewhat recurring or sensitive to something in the data.

I attached the logs. After a first failed trial I did a clean retried but still the same. Note that I have to constraint meryl memory. 

[H2B4.merqury.plot.spectra-cn.log](https://github.com/user-attachments/files/16627697/H2B4.merqury.plot.spectra-cn.log)

the blalbla_asm.hist is empty, all are empty except the simple H2B4.hist, any idea? 

EDIT: it worked, but I am not sure why maybe the first time I didn't clean properly.Sorry
