### ISSUE TITLE
Problems encountered when running Merqury with HiFi reads only

### ISSUE THREAD

**Issue by oddguyeee** [marbl/merqury#138]
Hi Arang,

My assembly was constructed with HiFi reads only, and I try to use Merqury to evaluate my assembly, but the error I have encountered:
```shell
/nfs_fs/nfs3/jiezhang/sunwu_genome/software/merqury-master/merqury.sh: line 18: /util/util.sh: No such file or directory
link: missing operand after ‘PF_HiFi_reads.meryl’
Try 'link --help' for more information.
read: 

No haplotype dbs provided.
Running Merqury in non-trio mode...

link: missing operand after ‘PF_defaut.p_ctg_chr.FINAL.fasta’
Try 'link --help' for more information.
asm1: 
out : PF_cov4_merqury
```
I try to check the directory `merqury-master/util/util.sh`, however, it exists. How can I do for that?

And this is my cmd:
```shell
best_k.sh 864364965
## k = 19.8257

meryl k=20 count ~/sunwu_genome/Assembly/P_florindae/PF_HiFi_fa/PF_hifi_read_total.fasta.gz output PF_HiFi_reads.meryl

merqury.sh PF_HiFi_reads.meryl PF_defaut.p_ctg_chr.FINAL.fasta PF_cov4_merqury
```

**Comment by brianwalenz** [comment]
Just guessing that you don't have environment variable MERQURY set to the directory where merqury is installed (`/nfs_fs/nfs3/jiezhang/sunwu_genome/software/merqury-master`).  See item 2 at https://github.com/marbl/merqury?tab=readme-ov-file#direct-installation.

**Comment by oddguyeee** [comment]
Thanks for your @brianwalenz remember, I have successful deal with this error, but the new trouble was found, all outputs were empty and I check the PF_cov4_merqury.spectra-cn.log from `logs` directory: 
```shell
...
Can't interpret 'PF_defaut.p_ctg_chr.FINAL.meryl': not a meryl command, option, or recognized input file.
usage: meryl ...
...
Can't interpret 'PF_defaut.p_ctg_chr.FINAL.0.meryl': not a meryl command, option, or recognized input file.
usage: meryl ...
```
I have checked output fold `PF_defaut.p_ctg_chr.FINAL.meryl`, no outputs in it, How can I deal with this issue?

**Comment by arangrhie** [comment]
Hi @oddguyeee , what do you get from
```
meryl statistics PF_HiFi_reads.meryl | head
```
Also check your `PF_defaut.p_ctg_chr.FINAL.fasta` can be opened with no issues.

If both gives you something reasonable, try to run merqury again in a clean folder.

**Comment by oddguyeee** [comment]
Hi @arangrhie ，

I get the output:
```sh
$meryl statistics PF_HiFi_reads.meryl | head
Found 1 command tree.
Number of 20-mers that are:
  unique                      0  (exactly one instance of the kmer is in the input)
  distinct                    0  (non-redundant kmer sequences in the input)
  present                     0  (...)
  missing         1099511627776  (non-redundant kmer sequences not in the input)

             number of   cumulative   cumulative     presence
              distinct     fraction     fraction   in dataset
frequency        kmers     distinct        total       (1e-6)
--------- ------------ ------------ ------------ ------------
```

And I try my cmd `$MERQURY/merqury.sh PF_HiFi_reads.meryl ../PF_defaut.p_ctg_chr.FINAL.fasta PF_cov4_merqury`, the output like this:
![image](https://github.com/user-attachments/assets/0c4bd453-b5b8-4787-9831-7677aeb0b0e8)
Finaly, the file PF_defaut.p_ctg_chr.FINAL.fasta was opened normally by busco, minimap2, et al. Is it need contain debris? I have extracted chromosome-level scaffolds from them.

If you need more information, please known me, thanks!

**Comment by arangrhie** [comment]
```
  unique                      0  (exactly one instance of the kmer is in the input)
  distinct                    0  (non-redundant kmer sequences in the input)
  present                     0  (...)
```

This means your meryl database is empty. Looks like your meryl count didn't work out well or got corrupted. Try that step again.

**Comment by oddguyeee** [comment]
@arangrhie ,

I have deal with this error, just a problem of `*.fastq.gz`. I used to combinate all fastq file in one file, but a unknow mistake lead total fastq seem non-including base quality information. Normal results were got by running with raw `*.fastq.gz` data.

Thanks!

**Comment by arangrhie** [comment]
Hy @oddguyeee,

You can count kmers on each fastq.gz files and merge at the end with `meryl union-sum` (Or use this [script](https://github.com/marbl/merqury/blob/master/build/union_sum.sh)). Alternatively, meryl count can take multiple input files, so `meryl count k=31 output reads.meryl *.fastq.gz` works as well.

**Comment by arangrhie** [comment]
Feel free to re-open in case you need more help. Closing it for now...
