### ISSUE TITLE
No output of completeness

### ISSUE THREAD

**Issue by lisagrigoreva** [marbl/merqury#139]
Hi,
I'm running merqury to access assembly completeness by comparing the k-mer library of PCR-free Illumina reads and polished and unpolished versions of the assembly. However, for some Illumina k-mer libraries I'm not getting a completeness plot and a they have a weird histogram. I was wondering what might be causing this. Does meryl/merqury not work with certain sequencing or coverage?
I expect the coverage to be around 50x.
Please find histogram for sample without completeness plot produced.
Thank you very much!
![without_compl_plot](https://github.com/user-attachments/assets/cfa4e519-f8f3-4157-96b1-3539c8c20d77)

**Comment by arangrhie** [comment]
Hi @lisagrigoreva, I have seen the exact same weird histogram when I had duplicated sequences in my two different fastq sets.
Check your PCR-free Illumina runs, and perhaps try to make meryl dbs again.
Before running Merqury, you could use `$MERQURY/plot/to_hist_for_plotting.sh illumina.k31.meryl F1_Illumina > F1.hist` and use it as an input and plot the sequencing data histogram with `$MERQURY/plot/plot_spectra_cn.R -f F1.hist -o F1_Illumina -t line`.

**Comment by lisagrigoreva** [comment]
I've checked Illumina reads, and they seem to be fine, although I merged 2 different lanes together (but they have different IDs in the Fasta header).  
Do you think I need to run data from different sequencing lanes separately for some reason?
![F1_Illumina ln](https://github.com/user-attachments/assets/7aae2883-b045-4e20-92e7-9f8eac7cfd86)

**Comment by arangrhie** [comment]
I'd recommend to just use one lane, looks like they sequenced the same library with some extra (unique to each library). Given your extreme coverage, should be fine to evaluate based on one lane.

Best,
Arang

**Comment by lisagrigoreva** [comment]
Dear @arangrhie , thank you! It's working with one lane.
