### ISSUE TITLE
Trio-binning like strategy for phasing transcriptome?

### ISSUE THREAD

**Issue by yjiang296** [marbl/merqury#142]
Hello!
I was trying to phasing F1 transcriptome to parent-of-origin using merqury, it seemed worked out. Does this practice make sense? I'm curious whether hapmers spanning across the RNAseq splicing site would affect the phasing performance.

In addition, I tried to build parents' meryl dbs using (1) WGS data (2) RNAseq data (3) WGS + RNAseq data, and found that practice (2) and (3) turned out to have weird results. Is it because RNA-seq doesn’t cover the genome as uniformly as WGS, which affects the frequency of k-mer occurrences and leads to phasing errors?

**Comment by arangrhie** [comment]
Hello @yjiang296,

This is an interesting question - I guess as long as the k size is smaller than an exon, and the exon happens to have a heterozygous variant that's distinguishable with parental kmers (or hapmers), the transcript will be binnable. Long-read based RNA-seq (kinnex, Iso-Seq, ONT RNA-seq, dRNA-seq, ...) will work better in this case compared to short-read based RNA-seq.

I think your interpretation is right, RNA-seq is not always guaranteed to capture all transcripts, and has a much smaller space than WGS to cover.
Why is (3) giving weird results..? This is a bit surprising, I was imagining that might give a more comprehensive list of kmers..  Perhaps some remnant RNAs containing transcription errors are increasing noise in the kmers space?

Best,
Arang

**Comment by yjiang296** [comment]
Thank you very much!
