### ISSUE TITLE
Error running merqury a message from util.sh

### ISSUE THREAD

**Issue by icruz1989** [marbl/merqury#15]
Hello, an amazing tool,

I am trying to run merqury but I get this error:

> ./merqury.sh: line 16: /util/util.sh: No such file or directory
> link: missing operand after 'read_db.meryl'
> Try 'link --help' for more information.
> read: 

> No haplotype dbs provided.
> Running Merqury in non-trio mode...

> link: missing operand after 'asm1.fasta'
> Try 'link --help' for more information.
> asm1: 
> out : test

> Get spectra-cn plots and QV stats

the command that I am using is

`./merqury.sh read_21.meryl datura.fasta test`

Also when i check logs I get this message: 

> ./merqury.sh: line 71: /eval/spectra-cn.sh: No such file or directory

any help?

Best regards
Ivan

**Comment by icruz1989** [comment]
Sorry, I already found the issue. It seems that I forgot set merqury
```
cd merqury
export MERQURY=$PWD
```
Cheers

**Comment by arangrhie** [comment]
Glad you found how to resolve the path :)
