### ISSUE TITLE
Adding $out to static file names to avoid filename conflicts

### ISSUE THREAD

**Issue by ASLeonard** [marbl/merqury#17]
Hi Arang,
This tool has been extremely useful in assessing new assemblies, but just wanted to offer a suggesting similar to issue #14. Currently, there are multiple places where files are written without prefixes, like 

 - completeness.stats
 - switches.txt
 - cutoffs.txt

This isn't an issue if merqury is run in individual folders, but does if for example a primary assembly and trio-binned assemblies are assessed in the same folder. Most of these files exist in scripts with an existing `$out` variable, and so I was able to modify it to work better for my use case by just using e.g. `$out.switches.txt`.

It may cause issues for other users who already directly use these file names, but otherwise I've experienced no issues in running merqury on multiple assemblies (from the same reads) in the same folder.

Many thanks,
Alex

**Comment by arangrhie** [comment]
Hi @ASLeonard,

The new merqury (latest on github) is now generating $out prefix to
* completeness.stats
* switches.txt

The `hapmers.sh` generates multiple files with no prefix, including `cutoffs.txt`.

I'd recommend to run this step in its own dedicated directory, as this has to be run only once and can be re-used for multiple assembly evaluations.

Thanks,
Arang
