### ISSUE TITLE
Help interpreting .spectra-cn.ln plots

### ISSUE THREAD

**Issue by kneubehl** [marbl/merqury#18]
Hi again,

I am looking over different .spectra-cn.ln plots of Illumina data for different strains of highly repetitive Borrelial genomes. The sequencing depth is between 100-150x but the kmer_multiplicity peak seems to be shifted by 50x or more and I am not sure if that makes a difference. Some of the plots look ok like the first plot I attached. Others look like the second plot where there is a plateau of read only kmers (I am assuming this is because that specific strain had a lower completeness, ~94%) and then I got one weird ones (the last one attached) where the plot of the kmers just plateaus (this happens in datasets with ~1000x coverage). Not sure if there are any issues out right with the second plot or if that is just showing that there are missing kmers in the assembly and I know there is something wrong with the last plot. Any guidance would be appreciated. Thanks! 
![baBA2 baBA2 spectra-cn ln](https://user-images.githubusercontent.com/58899964/97891880-f69cc800-1cf4-11eb-884b-a2d5482ba855.png)
![bcCo53_2 bcCo53_pilon8 spectra-cn ln](https://user-images.githubusercontent.com/58899964/97891917-01eff380-1cf5-11eb-9129-b414cdb5cf55.png)
![bvRMA01_2 bvRMA01_pilon1 spectra-cn ln](https://user-images.githubusercontent.com/58899964/97891941-07e5d480-1cf5-11eb-9bbf-b3a1db38cd21.png)

**Comment by arangrhie** [comment]
Hello,

I would suspect if the initial kmer counting had some issues when I see shifted kmer counts.
Is it possible that some of the same files were accidentally counted twice...?
Usually, we see clean line-like plots, not with zig-zags.
Are these non-canonical kmers?
How did you counted the kmers?

Plateau on the read-only kmers (black) from the second plot indicates the missing portion of the kmers in the second assembly.

The plateau on the third plot, where the 1-copy kmer (red) is plateauing, seems a bit strange, too.

**Comment by arangrhie** [comment]
Closing this as we haven't heard back about this issue for a while. Please reopen when it still persists.
