### ISSUE TITLE
Is it possible that switch error is zero ?

### ISSUE THREAD

**Issue by cchd0001** [marbl/merqury#22]
Hi Arang,

I evaluated  two NA12878 haplotype-aware assemblies  by pre-built meryl dbs(from [here](https://obj.umiacs.umd.edu/marbl_publications/merqury/index.html))  and all metrics are fine except the swtich errors are all zero.  I had evaluated one of the assembly with a self-built NA12878 meryl and pre-built hapmers and the swtich error was not zero but 0.14%. 

Below are the contents of  *stats  and switch.txt from pre-built meryl dbs of NA12878

```
NA12878.Pat	all	2232613826	2294572208	97.2998
NA12878.Mat	all	2233271654	2294572208	97.3285
both	all	2277921738	2294572208	99.2744
NA12878.Pat	NA12878.pat	17953494	18740902	95.7985
NA12878.Pat	NA12878.mat	32750	19878688	0.164749
NA12878.Mat	NA12878.pat	6469	18740902	0.0345181
NA12878.Mat	NA12878.mat	19022934	19878688	95.6951
both	NA12878.pat	17954819	18740902	95.8055
both	NA12878.mat	19025207	19878688	95.7066

NA12878.NA12878.Pat.100_20000	12,261	2,695,070,073	22	219,808	3,849,155	18,432,329	0	18144557	0%
NA12878.NA12878.Mat.100_20000	11,977	2,719,270,146	22	227,041	5,188,431	28,072,484	0	19170889	0%

NA12878.NA12878.Mat.100_20000 switch error rate (%) (Num. switches / Total markers found): 0	19170889	0%
```

Below are the contents of  *stats  and swiches.txt from self-built NA12878 meryl and pre-built hapmers.

```
ma_fab.mother	all	2232023738	2300926387	97.0054
pa_fab.father	all	2231414126	2300926387	96.9789
both	all	2276242413	2300926387	98.9272
ma_fab.mother	Pat.hapmer	6469	18740902	0.0345181
ma_fab.mother	Mat.hapmer	19022934	19878688	95.6951
pa_fab.father	Pat.hapmer	17953494	18740902	95.7985
pa_fab.father	Mat.hapmer	32750	19878688	0.164749
both	Pat.hapmer	17954819	18740902	95.8055
both	Mat.hapmer	19025207	19878688	95.7066

na12878.ma_fab.mother.100_20000	12,057	2,717,709,829	22	225,405	5,188,431	28,072,484	3215	19170841	0.0167703%
na12878.pa_fab.father.100_20000	12,614	2,684,659,568	22	212,832	3,683,712	18,432,329	26403	18144465	0.145515%

na12878.pa_fab.father.100_20000 switch error rate (%) (Num. switches / Total markers found): 26403	18144465	0.145515%
```

Although those file names are different , they are linked to the identical files.  I am sure the input fastas are identical and the software and parameters are the same.  The hapmers are also the same and the only difference is different NA12878 meryl db. 

Another NA12878 haplotype-aware assembly is pulibic data from :
ftp://ftp.dfci.harvard.edu/pub/hli/whdenovo/asm/NA12878-denovo-H1.fa.gz  and ftp://ftp.dfci.harvard.edu/pub/hli/whdenovo/asm/NA12878-denovo-H2.fa.gz 

The merqury I used  stays in 0d67a1d9f060f74573279b79929acf4fa3c3a684 ( Wed May 13 15:24:14 2020 -0400 ) .  Should I update it to the lastest ? 

I had evaluated HG002 with pre-built meryl dbs and the swith errors are not zero.

I do not know how to debug this . I appreciate any advice in advance.

Best wishes.

Lidong Guo

**Comment by arangrhie** [comment]
Hi Lidong,

Could you check if anything happened in the `*.phase_block*.log`, from the very beginning?
```
NA12878.Pat	NA12878.mat	32750	19878688	0.164749
NA12878.Mat	NA12878.pat	6469	18740902	0.0345181
```
The 3rd column have number of hapmers found from the unexpected haplotype, which may counted as switch errors if they fall in a phase block.

I wonder if the `bedtools sort` part died somehow...?

Try the latest merqury + latest meryl as described in the [README](https://github.com/marbl/merqury#experimental-version). 

This version is not using `bedtools sort` anymore as we had encountered several memory issues in this step.
Restart by running `$MERQURY/trio/phase_block.sh` in a clean directory,
for each haplotype fasta files using the hapmer dbs.
Should be done much faster than before.

Also, note that the output `switches.txt` files now have the haplotype extension.
I think there was a bug where I didn't use `>>` and used `>` for writing the switch error summary.
FYI, the switch error rates for both haplotype fasta files can be found in the last column of the *phase_block.stats files.

**Comment by cchd0001** [comment]
Hi Arang,

I found this in phase_block.log 

```

Loading genome: /merqury/merqury_NA12878_1/NA12878-denovo-H1.fasta.fai
No observers for event type: class org.broad.igv.event.GenomeChangeEvent
ERROR [2020-11-18T16:09:49,885]  [GenomeListManager.java:411] [main]  Error fetching genome list:
java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:?]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[?:?]

....

Loading required package: argparse
Loading required package: ggplot2
Registered S3 methods overwritten by 'ggplot2':
  method         from
  [.quosures     rlang
  c.quosures     rlang
  print.quosures rlang
Loading required package: scales
Error in read.table(dat, header = TRUE) :
  duplicate 'row.names' are not allowed
Calls: blob_plot -> read.table
Execution halted
v.jar:?]
        at org.broad.igv.tools.IgvTools.main(IgvTools.java:255) [igv.jar:?]

 at org.broad.igv.tools.IgvTools.main(IgvTools.java:255) [igv.jar:?]
Error fetching genome list:
java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:?]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[?:?]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[?:?]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[?:?]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403) ~[?:?]

```

I also check the log of  HG002  and found a differnt error log 

```

Loading genome: /merqury_HG002_1/NA24385-denovo-H1.fasta.fai
INFO [2020-11-12T14:20:06,648]  [IGVEventBus.java:80] [main]  No observers for event type: class org.broad.igv.event.GenomeChangeEvent
No observers for event type: class org.broad.igv.event.GenomeChangeEvent
ERROR [2020-11-12T14:20:26,848]  [GenomeListManager.java:411] [main]  Error fetching genome list:
java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:?]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[?:?]
....
gvTools.doCount(IgvTools.java:849) [igv.jar:?]
        at org.broad.igv.tools.IgvTools.run(IgvTools.java:372) [igv.jar:?]
        at org.broad.igv.tools.IgvTools.main(IgvTools.java:255) [igv.jar:?]
Error fetching genome list:
java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:?]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[?:?]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[?:?]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[?:?]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403) ~[?:?]
        at java.net.Socket.connect(Socket.java:609) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:289) ~[?:?]
        at sun.net.NetworkClient.doConnect(NetworkClient.java:177) ~[?:?]
....
```

They both have the java ERROR ( IGV tools failure ? ) but  NA12878 also has a R ERROR when draw blob graph .

I will try trio/phase_block.sh and report the result later.

Thanks a lot.

Lidong Guo

**Comment by cchd0001** [comment]
Hi Arang,

I restart by running $MERQURY/trio/phase_block.sh in a clean directory and get the non-zero switch errors now. The switch errors for data set1 are exact match self-built meryl dbs result.  

Thanks a lot

Lidong Guo
