### ISSUE TITLE
Executing scripts using sh is giving errors.

### ISSUE THREAD

**Issue by mnshgl0110** [marbl/merqury#23]
Hi,
I am trying to use Merqury (hapmers.sh specifically) but am getting errors like:

`/srv/netscratch/dep_mercier/grp_schneeberger/software/merqury-1.1/build/intersect.sh: 3: /srv/netscratch/dep_mercier/grp_schneeberger/software/merqury-1.1/build/intersect.sh: [[: not found`

This is happening because the scripts (intersect.sh, filt.sh etc) are being called [using SH](https://stackoverflow.com/questions/12230690/string-comparison-in-bash-not-found). Indeed, when I change the specific lines from ```sh $MERQURY/build/intersect.sh $child_meryl $hap2.only.meryl $hap2.inherited``` to ```bash $MERQURY/build/intersect.sh $child_meryl $hap2.only.meryl $hap2.inherited```, it works fine. As all scripts are supposed to be run using bash (they all have #!/bin/bash), I am not sure why they are being called using sh. If there is no specific reasoning for it, then it would be great if the commands are changed to use bash instead of sh.

**Comment by arangrhie** [comment]
Hi @mnshgl0110 ,

Sorry for the frustration! Yes, we noted that issue and fixed it in [dd31ab5d86d430335f43bde5a599c82403706fde](https://github.com/marbl/merqury/commit/dd31ab5d86d430335f43bde5a599c82403706fde) and [78747d01aff86adaea3eede3e0bf9b1a4f7d69f1](https://github.com/marbl/merqury/commit/78747d01aff86adaea3eede3e0bf9b1a4f7d69f1).

It will be more stable in the upcoming 1.2 release.
