### ISSUE TITLE
Meryl new-old

### ISSUE THREAD

**Issue by duhuipeng** [marbl/merqury#25]
Dear author

I am operating on the updated meryl now
I'm thinking of two data sets, specific kmer for each individual
My code are as follows
1. meryl count k=21 reads1.fasta oiutput k1_21.meryl
2. meryl count k=21 reads2fasta output k2_21.meryl
3. meryl difference output k1_not_k2.meryl k1_21.meryl k2_21.meryl
But now I want to convert these specific folders into sequences, There was a mistake in my operation
my code:
meryl threads=25  print k1_not_k2.meryl/ |awk '{if (match($1,">")) { COUNT=substr($1, 2, length($1)); } else {print $1" "COUNT}}' |awk '{if ($NF < 150) print $0}' >  k1.counts
But k1.counts generated 0

I look forward to your reply

**Comment by brianwalenz** [comment]
I'm not very fluent in awk, but it looks wrong.  `meryl print` doesn't write fasta:
```
> meryl print sample.meryl | head
ACGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA     40
ACGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG     2
ACGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGA     2
...
```
Does `meryl print k1_not_k2.meryl` show anything?

Are reads1 and reads2 actually different?  Try something like `meryl print difference k1_21.meryl greater-than 20 k2_21.meryl` - that is, only remove the more frerquent kmers, leaving all the noise kmers.

**Comment by duhuipeng** [comment]
yes, I am trying to extract the specific kmer of each of the two data
I'm learning from an article
But his article used the version older, but I' m using the new version now, and there's a problem with extracting specificity kmer this step
The code in the article is like this
![image](https://user-images.githubusercontent.com/58722433/105436723-aa7d7600-5c9a-11eb-9b8e-cd93d6a43372.png)
meryl -Dt -n 25 -s k12.only |awk '{if (match($1,">")) { COUNT=substr($1, 2, length($1)); } else {print $1" "COUNT}}' |awk '{if ($NF < 150) print $0}' >  k12.counts

meryl -Dt -n 25 -s o157.only |awk '{if (match($1,">")) { COUNT=substr($1, 2, length($1)); } else {print $1" "COUNT}}' |awk '{if ($NF < 150) print $0}' >  o157.counts

But at the last step, there's a problem this specific binary file (k12.only) into a sequence,  generated 0
I saw that it was extracted in the article
![image](https://user-images.githubusercontent.com/58722433/105436999-342d4380-5c9b-11eb-9278-cba1f5ce2dba.png)

**Comment by duhuipeng** [comment]
I hope to get your advice and look forward to your reply

**Comment by duhuipeng** [comment]
![image](https://user-images.githubusercontent.com/58722433/105437802-b4a07400-5c9c-11eb-99ce-afd8c9f41baa.png)
According to the code you provided(meryl print k1_not_k2.meryl) the result of my running is as follows above

**Comment by duhuipeng** [comment]
![image](https://user-images.githubusercontent.com/58722433/105438736-87ed5c00-5c9e-11eb-9b25-98c57d1d44c2.png)
According to your advice, this is the result of my run
The results are as follows;
![image](https://user-images.githubusercontent.com/58722433/105438826-b5d2a080-5c9e-11eb-9100-4d4a8dbddc53.png)
I don't know where I I do n' t know where I was wrong, could you give some advice

Best

**Comment by duhuipeng** [comment]
Daer author

Unupdated meryl can only accept fa sequence formats?

**Comment by brianwalenz** [comment]
The meryl part looks like it is working.

I think the awk is converting from a format (as used in the older meryl) like:
```
>15
ACGTACGTACGT
```
to that used in the newer meryl (`ACGTACGTACGT 415`).  Thus, I  suspect the awk isn't needed anymore.


Meryl can read fasta or fastq, uncompressed or compressed.

**Comment by duhuipeng** [comment]
yes, I also found this issue, I got it
But I'm curious why I used the author's data and the results were different,and it's so different
Do I have a problem in this step of different ?  But I feel that my code is not wrong

**Comment by skoren** [comment]
The article is using an old version of Meryl, the output format and parameters aren't going to match at all. If you want to reproduce the article, you should use the older version of meryl. Run meryl without options to get help on the current syntax. You'll need to update the commands to match the new syntax as @brianwalenz pointed out, the awk is not correct anymore and is relying on a print format that doesn't exist which is why your command isn't working.

**Comment by duhuipeng** [comment]
Thank you ,got it
