### ISSUE TITLE
block_n_stats.sh

### ISSUE THREAD

**Issue by duhuipeng** [marbl/merqury#26]
Dear author
I'm running the example you' ve given, but I ran the script with an error, as follows:
![image](https://user-images.githubusercontent.com/58722433/105865273-b5832e00-602d-11eb-8b44-980f5113c983.png)
I added a path to the environment variable, why is it still like this
![image](https://user-images.githubusercontent.com/58722433/105865464-ec594400-602d-11eb-9b56-cadca83ede06.png)
Hope to get your reply

**Comment by duhuipeng** [comment]
The running code is as follows:
 bash /home/Mpzhang/HpDu/merqury-1.1/merqury.sh F1.k18.meryl col0.hapmer.meryl cvi0.hapmer.meryl athal_COL.fasta athal_CVI.fasta test

**Comment by skoren** [comment]
See issue #14, you can remove the module load commands. The module warning won't affect the run as long as appropriate sam/bamtools + R + meryl are in your path.
