### ISSUE TITLE
Low consensus quality value

### ISSUE THREAD

**Issue by shehongbing** [marbl/merqury#28]
Hi, 
      it's a so great tool. I used it to measure the QV, and the value is only 23.3546. And i notice that  the QV is more 30 in our example data. So should i need to further polish my genome using Illumina data?

Thanks 

Hongbing She

**Comment by arangrhie** [comment]
Hi @shehongbing , Q23 seems pretty low. The Q30 examples are also unpolished results.
To get reasonable gene annotations, we find that Q40 is the mathematical inflection point between where genes go from usually containing an error to usually not, and thus recommend to polish or re assemble to go over Q40 for the genomes from the VGP.

See [Koren, S., Phillippy, A.M., Simpson, J.T. et al. Reply to ‘Errors in long-read assemblies can critically affect protein prediction’. Nat Biotechnol 37, 127–128 (2019)](https://doi.org/10.1038/s41587-018-0005-y) for more details.
