### ISSUE TITLE
Unable to run meryl with a for script

### ISSUE THREAD

**Issue by SheepwormJM** [marbl/merqury#29]
Hi,

Thanks for Merqury! 

I was following your example script on https://github.com/marbl/merqury/wiki/1.-Prepare-meryl-dbs and found that it would not work. 

I changed it to: 

for i in $i.fastq.gz ;
do
  # 1. Build meryl dbs
  /export/home2/jmi45g/anaconda3/envs/Merqury/bin/meryl count k=20 $i.fastq.gz output $i.meryl ;
done

at which point it seemed to want to run, but was doing something strange with my files and was complaining that it wasn't sure what to do with a file of .fastq.gz.fastq.gz

I've run it with them individually, which has worked fine, they just didn't seem able to handle my for script. 

Thanks.

**Comment by arangrhie** [comment]
Hi @SheepwormJM , the code in the wiki is a pseudo-code.

In bash, you need to give exact 'things' after `in`.

```
ls *.fastq.gz > input.fofn
for f in $(cat input.fofn)
do
i=${f/.fastq.gz/}
/export/home2/jmi45g/anaconda3/envs/Merqury/bin/meryl count k=20 $f output $i.meryl ;
done
```
should do what you wanted to do. Google for `bash for loop`.

**Comment by SheepwormJM** [comment]
Thanks @arangrhie I will take a look!
