### ISSUE TITLE
Issue with finding util.sh

### ISSUE THREAD

**Issue by SheepwormJM** [marbl/merqury#30]
Hi,

When running merqury I run into a problem. I can run

merqury.sh --help 

and get the help manual no problem. 

But when I try to run it with my actual files (a read_db.meryl, genome.fasta output_prefix) it complains about three things, of which two I am thinking might follow on from the first.

~/Merqury/share/merqury/merqury.sh: line 16: /util/util.sh: No such file or directory
link: missing operand after `reads_jenni.meryl'
Try `link --help' for more information.
link: missing operand after `jenni.fasta'
Try `link --help' for more information.

The script is:

#!/bin/sh
#PBS -l walltime=30:00:00
#PBS -l cput=30:00:00
#PBS -l nodes=1:centos6
#PBS -d ~/Jenni_genome_Nov2020/Merqury

export PATH="~/Merqury/share/merqury/:$PATH"

~/Merqury/share/merqury/merqury.sh reads_jenni.meryl jenni.fasta jenni

In the ~/Merqury/share/merqury directory I have both merqury.sh and util/util.sh

If I do: 

more $pwd/util.sh 

I get the util.sh script. And when I list the contents of the util folder the util.sh has a size (i.e. its not 0). 

So I wondered if it needed the $MERQURY in the merqury.sh script specified and I tried to do it by inserting a line in my script above the merqury.sh command: 

~/Merqury/share/merqury=$MERQURY

But it threw up an error and said that there was No such file or directory for this. 

Any advice would be great. Thanks!

**Comment by SheepwormJM** [comment]
Quick edit. 

Found an older closed thread about the same thing. 

Changed my MERQURY path to: 

export MERQURY="~/Merqury/share/merqury:$MERQURY"

but still get the same error. Also when I have 

export MERQURY="~/Merqury/share/merqury/:$MERQURY"

Any ideas? (btw the ~ I have just used to replace the exact path in my script which is quite long and boring)

**Comment by arangrhie** [comment]
Hi @SheepwormJM ,

You need to export `MERQURY` as an environment variable, perhaps globally set in your `~/.bash_profile`. See
https://github.com/marbl/merqury#direct-installation

**Comment by SheepwormJM** [comment]
Thanks @arangrhie! I've now slightly changed my export line and it is now working. (Then failed but once I also exported a different path to my meryl it is looking like it is working again). Thanks for your help.

For anyone else, these are my current export lines: 

export PATH="/export/home2/jmi45g/anaconda3/envs/Merqury/share/merqury:$PATH"
export PATH="/export/home2/jmi45g/anaconda3/envs/Merqury/bin:$PATH"

export MERQURY=/export/home2/jmi45g/anaconda3/envs/Merqury/share/merqury
