### ISSUE TITLE
Awk error and looking for more docs/tutorial on merqury

### ISSUE THREAD

**Issue by Tipplynne** [marbl/merqury#32]
Good day and thank you sharing great software!

I am trying merqury for the first time. I  installed both Meryl and Merqury but i am having trouble with the first step estimating ideal kmer size:

sh $MERQURY/best_k.sh 924902646 [tolerable_collision_rate=0.001]

But after I run this line I get an error:

`genome: 924902646
tolerable collision rate: [tolerable_collision_rate=0.001]
awk: cmd. line:1: (FILENAME=- FNR=1) fatal: division by zero attempted`

Have I missed an argument in the command?

Also I was wondering if there are any currently available merqury tutorials or examples available online?

Thanks and kind regards
Crystal

**Comment by arangrhie** [comment]
`[tolerable_collision_rate]` means it is optional.
No need to give values if you are using the same `tolerable_collision_rate`.

Run either
```sh $MERQURY/best_k.sh 924902646```

Or 
```sh $MERQURY/best_k.sh 924902646 0.001```

**Comment by Tipplynne** [comment]
Dear Arangrhie

Thanks for your fast response, it worked (k=19.8745). Im not sure on how the examples for the docs are indexing reads/files so I have written out each line separately, similarly to how you did this in a response to someone else's issue eg.

`meryl k=$k count output K_flavicollis_f.meryl K_flavicollis_f_FKDL202605743-1a-7UDI301-AK1847_H7W25CCX2_L6_1.fq.gz memory=48 threads=24`

But when I run this, the output `K_flavicollis_f.meryl` is empty, and the job file gives me the list of params for running meryl with the error `Don't know what to do with 'k='.`

So I changed to k=20, and now its running, I guess the decimal point is the problem? 

Thanks again and kind regards
Crystal

**Comment by arangrhie** [comment]
Hello Crystal,

Yes, a k is expected to be an integer, by the definition of a k-mer.
k=20 should be fine.

**Comment by Tipplynne** [comment]
Dear Rhie Arang

Thank you so much! It's working, and now I have a lot of data to analyse! I've already begun, so far have some nice data  that Im excited about. But some of my plots (spectra-cn, longread promethion assemblies vs short reads from illumina) are showing unusual kmer distributions. Would you be willing to look at few and give me some insight into what Im looking at? Would it be ok to share them here in this thread?

Thanks again and kind regards
Crystal

**Comment by arangrhie** [comment]
Cool! Sure, I think that will help other users too to understand plots and assembly evaluation in general.

**Comment by arangrhie** [comment]
@Tipplynne feel free to open a new issue in case you need help interpreting your results!
