### ISSUE TITLE
Hap_blot.sh

### ISSUE THREAD

**Issue by duhuipeng** [marbl/merqury#33]
When I run merqury, the second step:  hap_blob.sh ,the problem arises
This is the code I run:
/home/duhuipeng/DHP/merqury-1.1/merqury.sh /home/duhuipeng/DHP/DRC/DRC.SON.k21.meryl/ ../../DRC.father.k21.meryl/ ../../DRC.mother.k21.meryl/ ../father_purged.fasta  ../purged_mo.fasta test-2
the error as follow in hap_blob
![image](https://user-images.githubusercontent.com/58722433/110190067-7df17800-7e5c-11eb-975f-346b9678ae91.png)
![image](https://user-images.githubusercontent.com/58722433/110190078-86e24980-7e5c-11eb-8766-7ac15f0ae470.png)
![image](https://user-images.githubusercontent.com/58722433/110190096-96fa2900-7e5c-11eb-9694-bdc405047590.png)
![image](https://user-images.githubusercontent.com/58722433/110190112-a5e0db80-7e5c-11eb-85ed-2864e320cdee.png)
![image](https://user-images.githubusercontent.com/58722433/110190121-b1340700-7e5c-11eb-909a-f6cbd8e200ed.png)
at first I thought core dump was out of memory, but I found that I couldn't run when I used the size of 3T memory. How can I solve this problem?
Because I want to draw a picture of its phase separation,But this step is wrong is not drawn, I hope to get your advice.

Looking forward to your reply!
Best

**Comment by arangrhie** [comment]
Hello @duhuipeng,

Please use the inherited hapmers instead of the full maternal / paternal dbs.
See the section in here:
https://github.com/marbl/merqury/wiki/1.-Prepare-meryl-dbs#3-build-hap-mer-dbs-for-trios

I'll close the issue opened in meryl repo.

Thanks,
Arang

**Comment by duhuipeng** [comment]
I don't understand. Do you mean my input file becomes as follows
when I meryl union the patrilineal,Should I input it like this ?
/home/duhuipeng/DHP/merqury-1.1/merqury.sh /home/duhuipeng/DHP/DRC/DRC.SON.k21.meryl/ union.k21.meryl ../father_purged.fasta ../purged_mo.fasta test-2
Do work like this ?It's feel strange

**Comment by arangrhie** [comment]
No, I meant to prepare the hapmer dbs first.
Make a directory and symlink your maternal and paternal meryl dbs, and run `$MERQURY/trio/hapmers.sh`.
```
ln -s /path/to/your/DRC.mother.k21.meryl Mother.meryl
ln -s /path/to/your/DRC.father.k21.meryl Father.meryl
ln -s /path/to/your/DRC.SON.k21.meryl Son.meryl
sh $MERQURY/trio/hapmers.sh Mother.meryl Father.meryl Son.meryl
```

And use the inherited, filtered hapmers (they will be symlinked as Mother.hapmers.meryl and Father.hapmers.meryl).
Given the meryl db size, I assume the `maternal.meryl` and `paternal.meryl` were directly collected using meryl from the full sequencing data set.
The `hapmers.sh` produces the inherited kmer spectrum, as described in the wiki page and in the Merqury paper.

The hapmers are haplotype specific kmers, which you'd want to evaluate the assembly against.
So, after producing the hapmer.meryl dbs, run
```
./merqury.sh Son.meryl Mother.hapmers.meryl Father.hapmers.meryl father_purged.fasta purged_mo.fasta test
```

**Comment by duhuipeng** [comment]
I got it ,Thanks

**Comment by arangrhie** [comment]
Great, let me know when you encounter other issues.

**Comment by duhuipeng** [comment]
![image](https://user-images.githubusercontent.com/58722433/110198969-0ee24680-7e91-11eb-8850-98861784cc61.png)
Dear author 
I guess if your place is reversed, it should correspond to my meryl file

**Comment by duhuipeng** [comment]
Dear author
When I run merqury, the second step: hap_blob.sh ,the problem also arises
![image](https://user-images.githubusercontent.com/58722433/110228266-b7001a00-7f3a-11eb-8066-565a6f6bc867.png)
![image](https://user-images.githubusercontent.com/58722433/110228412-e5cac000-7f3b-11eb-9949-2a99f3e4d5fb.png)
This is the code I run:
/home/duhuipeng/DHP/merqury-1.1/merqury.sh Son.meryl Mother.hapmers.meryl Father.hapmers.meryl purged_mo.fasta father_purged.fassta test

**Comment by duhuipeng** [comment]
![image](https://user-images.githubusercontent.com/58722433/110228540-db5cf600-7f3c-11eb-90d1-81401df7d4e0.png)
![image](https://user-images.githubusercontent.com/58722433/110228541-db5cf600-7f3c-11eb-84f4-9e4842a5576f.png)
![image](https://user-images.githubusercontent.com/58722433/110228538-db5cf600-7f3c-11eb-87e2-aca7dcae1e2c.png)
![image](https://user-images.githubusercontent.com/58722433/110228539-db5cf600-7f3c-11eb-8fc5-3c1d1c9d4469.png)
![image](https://user-images.githubusercontent.com/58722433/110228547-ea43a880-7f3c-11eb-80f0-2fbaa22fa686.png)
This is all I have generated when running the command as above

**Comment by duhuipeng** [comment]
Dear author
I saw his error saying it couldn't connect Mother.hampers.meryl,saying it already exists
I looked at hapmer.sh code again, it generated files should be hamper.Father.meryl files,It shouldn't be hampers.Father.meryl .
I  feel like my input should be 
./merqury.sh Son.meryl Mother.hapmer.meryl Father.hapmer.meryl father_purged.fasta purged_mo.fasta test
I see what you're giving  ./merqury.sh Son.meryl Mother.hapmers.meryl Father.hapmers.meryl father_purged.fasta purged_mo.fasta test
Do you feel that this input is the reason Is the error caused?
Looking forward to your reply

**Comment by arangrhie** [comment]
Yes, you are correct. Use `Mother.hapmer.meryl` and `Father.hapmer.meryl` instead.
Apologies about the confusion.

**Comment by duhuipeng** [comment]
Dear author
![image](https://user-images.githubusercontent.com/58722433/149603273-9e4a98b5-7809-43d7-9fe4-7ad43fcd7044.png)
![image](https://user-images.githubusercontent.com/58722433/149603237-f7697de0-ecd9-4c6e-8663-4b248559eef3.png)
this is my code :
/home/duhuipeng/DHP/merqury-1.1/merqury.sh ../ALL.k21.meryl/ ../Mo_ALL.k21.hapmer.meryl/ ../Fa_ALL.k21.hapmer.meryl/ ../../DrcSonPhased_hap2.fasta ../../DrcSonPhased_hap1.fasta DRC
But the above problem has emerged ,I  guess it is insufficient memory leading to core dump.
I would like to consult what parameters can be set to limit it memory size and  make it work properly

Best
huipengDu
