### ISSUE TITLE
Error reported when run meryl, but looks like it has run fine

### ISSUE THREAD

**Issue by SheepwormJM** [marbl/merqury#39]
Hi,
I've just been running meryl on some fastq.gz files, and for one of the files I got the following errors in the log. But it looks like it has completed fine, and I have the output files. Can I just ignore it? 

gzip: ERR126028_2.fastq.gz: invalid compressed data--crc error

gzip: ERR126028_2.fastq.gz: invalid compressed data--length error

Thanks,
Jenni

**Comment by arangrhie** [comment]
Hi Jenni,

Could you try unzipping first, and run meryl on the fastq file?
I wonder if the gz file was corrupted, and meryl just silently ignored the sequences past that corrupted bit.
If this was the case, the unzipping will tell you if the gz file was corrupted, or the meryl db size would be different.

**Comment by SheepwormJM** [comment]
Thanks Arang, I’ll give that a go.
Jenni

**Comment by SheepwormJM** [comment]
Hi Arang,
Just to update... 

gunzip didn't work and produced the same errors. I re-downloaded the file from ENA and was able to gunzip the new file. I ran meryl on this, and the merylIndex file is about 30k larger. 

I'll run merge using this new file. 

Thanks very much for your help! 
Jenni
