### ISSUE TITLE
exclude read for HiC scaffolding

### ISSUE THREAD

**Issue by baozg** [marbl/merqury#42]
Hello, @arangrhie 

In the VGP preprint, you use `exclude_read.sh` for binning the HiC reads. But in my trio project, we only have child hifi reads and parents Illumina reads. 

So can I just use the paternal or maternal spciefic reads or using HiFi kmer to get hapmer?

Thanks,
Zhigui Bao

**Comment by arangrhie** [comment]
Hi @baozg ,

Yes, you could try the hapmer.sh using HiFi kmer if that is your only option for the child.
Then, use the hapmers with the exclude_reads.sh to exclude reads with one haplotype from your hifi reads.

Thanks,
Arang

**Comment by baozg** [comment]
Thank for the promptly repsone, I will try `hapmer`.
