### ISSUE TITLE
Getting a bed file of kmers in assembly but not in reads

### ISSUE THREAD

**Issue by mwykes** [marbl/merqury#43]
Firstly, thanks for this very useful tool! 

I'd like to create a bed file annotating kmers in my assembly which are not in the reads. 

As far as I can see, this is done as part of [spectra-cn.sh](https://github.com/marbl/merqury/blob/master/eval/spectra-cn.sh#L139) by running 
```
meryl-lookup -bed -sequence $asm_fa -mers ${asm}.0.meryl > ${asm}_only.bed
```
However, when I try running this, meryl-lookup gives me an error message:
```
Unknown option '-bed'.
No report-type (-existence, etc) supplied.
```
I'm using meryl-lookup v1.2 within the merqury conda package. 

Does meryl-lookup no longer support bed output, or am I missing something? Is there another way to do this? 

Thanks,
Mike

**Comment by arangrhie** [comment]
Hi Mike,

Use the latest meryl from https://github.com/marbl/meryl, or use the merqury script in your conda package.

Thanks,
Arang

**Comment by mwykes** [comment]
Thanks @arangrhie. 

In the version of spectra-cn.sh in my conda environment, I found an alternative command that did work

```
meryl-lookup -dump -memory 6 -sequence $asm_fa -mers ${asm}.0.meryl | awk '$(NF-4)=="T" {print $1"\t"$(NF-5)"\t"($(NF-5)+21)}' > ${asm}_only.bed
```
Apologies for not checking this before. 

Mike
