### ISSUE TITLE
kmer completeness file empty

### ISSUE THREAD

**Issue by u2progress** [marbl/merqury#45]
Hello,

When I run merqury, it runs without error, I get all the spectra-cn plots, and the qv file populates okay, I can even see meryl dbs generated for my assemblies, but the kmer completeness file is empty. Also, the asm only wig files are empty as well. 
What do you think the issue could be? 

Thank you,
Unnati

**Comment by arangrhie** [comment]
Hello Unnati,

Can you check or post the spectra-cn log file?
Wonder if this step failed: `java -jar -Xmx256m $MERQURY/eval/kmerHistToPloidyDepth.jar reads.hist`
Or meryl ran out of memory or something...

In addition, a spectra-cn plot would help understand what happened.

Thanks,
Arang

**Comment by u2progress** [comment]
Hi Arang, 

Thank you for getting back to me. I looked through the spectra-cn log file and it turned out to be something really simple. The way I had named my output for meryl, the read database ended up being named as {reads}.meryl.k18.meryl causing all the issues. 
Running okay now. 

Thanks again, 
Unnati
