### ISSUE TITLE
Quality value equal to Inf

### ISSUE THREAD

**Issue by bistace** [marbl/merqury#48]
Hello and thank you for developing Merqury,

I have launched it on a plant genome and it finishes without crashing. However, the QVs I obtain are equal to inf, with k-mers specific to the assemblies equal to 0. The `_only.bed` and `_only.wig` files of the assembly are also empty. Here is the command I launched:
```
bash merqury/merqury.sh /env/cns/bigtmp2/reapr_pahang/reads/reads.meryl assembly_v2.fasta merqury_v2
```

Here is the content of the ` .qv` file:
```
assembly_v2	0	405325924	inf	0
```

And finally, here is the spectra-cn log, could you please help me solve this issue?
[merqury_v2.spectra-cn.log](https://github.com/marbl/merqury/files/6554290/merqury_v2.spectra-cn.log)

**Comment by arangrhie** [comment]
Hello, @bistace what is the genome size?
Seems like you picked k=11, which seems too small.
Of note, a 100 Mb genome requires k=18 ~ 19 under a tolerable collision rate of 0.001.

You could use `$MERQURY/best_k.sh` to estimate the recommended kmer size.

Best,
Arang

**Comment by bistace** [comment]
You're right! I will launch everything again with k=21 as suggested by `best_k.sh` and report back to you if that solved my problem.

**Comment by bistace** [comment]
Hello,

changing the k-mer size to 21 corrected the errors and Merqury was able to finish successfully, as you predicted. Thanks a lot for your help!
