### ISSUE TITLE
conda install

### ISSUE THREAD

**Issue by shannonekj** [marbl/merqury#5]
I'm really excited merqury! Will you be supporting a conda install of the program any time soon?

**Comment by brianwalenz** [comment]
Probably not.  We have no experience using conda, let alone adding a new module to it.  You might want to ask one of the conda maintainers if they'll import merqury.

I'll leave this open asking for community help though.

**Comment by arangrhie** [comment]
Hi @shannonekj,

Thanks to our collaborator Chai(@Akarachai) and Trevor (@tpesout) from the VGP,
we have something that might be an interest for you.
Trevor made a wdl script that runs on the docker image that Chai made:

https://github.com/tpesout/vgp-assembly/blob/master/wdl_pipeline/wdl/tasks/merqury.wdl
https://github.com/VGP/vgp-assembly/blob/master/dx_applets/merqury/docker/Dockerfile

Chai made a docker image earlier, however it runs only the QV estimate. There will be an update soon that runs the full Merqury pipeline.
https://quay.io/repository/chai/merqury

Thanks for sharing your excitements! Hope this helps.

**Comment by Arkarachai** [comment]
@shannonekj I plan to update the docker image this weekend. It should have all the functionality of mercury starting next week.

**Comment by shannonekj** [comment]
Thanks @Arkarachai and @arangrhi ––A Docker image is certainly helpful and even more so with the full functionality of mercury. Looking forward to using it!

**Comment by Arkarachai** [comment]
@shannonekj I just push a new docker image with tag 0.0.2.  The ENTRYPOINT is just a /bin/bash, so you would have to overwrite with your own command of interest. The merqury is at the root. If you don't have a strong preference of workflow language, we recommend WDL since Trevor and I will make workflows in this language for the VGP group, so you can use our workflow. Otherwise, feel free just to use our Docker directly. Please give a try and let us know if you run into any issue.

**Comment by aboyher** [comment]
> 
> 
> @shannonekj I just push a new docker image with tag 0.0.2. The ENTRYPOINT is just a /bin/bash, so you would have to overwrite with your own command of interest. The merqury is at the root. If you don't have a strong preference of workflow language, we recommend WDL since Trevor and I will make workflows in this language for the VGP group, so you can use our workflow. Otherwise, feel free just to use our Docker directly. Please give a try and let us know if you run into any issue.

Does the docker make the meryl databases by chance?

**Comment by aboyher** [comment]
> 
> 
> @shannonekj I just push a new docker image with tag 0.0.2. The ENTRYPOINT is just a /bin/bash, so you would have to overwrite with your own command of interest. The merqury is at the root. If you don't have a strong preference of workflow language, we recommend WDL since Trevor and I will make workflows in this language for the VGP group, so you can use our workflow. Otherwise, feel free just to use our Docker directly. Please give a try and let us know if you run into any issue.

Does the docker make the meryl databases by chance?

**Comment by aboyher** [comment]
> > @shannonekj I just push a new docker image with tag 0.0.2. The ENTRYPOINT is just a /bin/bash, so you would have to overwrite with your own command of interest. The merqury is at the root. If you don't have a strong preference of workflow language, we recommend WDL since Trevor and I will make workflows in this language for the VGP group, so you can use our workflow. Otherwise, feel free just to use our Docker directly. Please give a try and let us know if you run into any issue.
> 
> Does the docker make the meryl databases by chance?

I think I answered my own question, it seems like it does. But I'm really not familiar with docker's any chance you could provide an example command for running _submit_build.sh ?

**Comment by aboyher** [comment]
> > > @shannonekj I just push a new docker image with tag 0.0.2. The ENTRYPOINT is just a /bin/bash, so you would have to overwrite with your own command of interest. The merqury is at the root. If you don't have a strong preference of workflow language, we recommend WDL since Trevor and I will make workflows in this language for the VGP group, so you can use our workflow. Otherwise, feel free just to use our Docker directly. Please give a try and let us know if you run into any issue.
> > 
> > 
> > Does the docker make the meryl databases by chance?
> 
> I think I answered my own question, it seems like it does. But I'm really not familiar with docker's any chance you could provide an example command for running _submit_build.sh ?

Answered my own question yet again. Sorry about that!

**Comment by Arkarachai** [comment]
I have never used the running _submit_build.sh but I can give guideline on how to call Docker image in general.
After you install Docker and pull docker image to your machine, you can decide if you want to run Docker in interactive mode or in non-interactive mode.
The command for interactive is like this with -it. the -v is the mounting point that matches between your local repo and repo you want it to appear inside Docker image. You would need to create /all_count in your local computer and put input data there.
sudo docker run -it -v /all_count:/all_count --entrypoint "/bin/bash" quay.io/chai/merqury:0.0.2
Once you run it, you will be in Docker container. You can negivate to /merqury and run the program you want, and put results in /all_count which will show up in your /all_count of your local computer. 
For the beginning, this would be easier than non-interactive mode.

**Comment by EdHarry** [comment]
I can create a conda recipe if you're still interested. I've already updated meryl to v1.0 on [bioconda](https://anaconda.org/bioconda/meryl/files) (I couldn't get the OSX build to work because of issues with omp, maybe the developers want to take a look at the recipe if they want the OSX version to be available), and all the other dependencies are available.

The only issue is how you want to expose all the scripts to users, you can't rely on users knowing the installation path, and creating post-environment-activation scripts / new environmental variables is highly discouraged by the bioconda community. I'd recommend you just place / link all callable scripts into the bin directory of the conda environment, but it's up to you.

**Comment by shannonekj** [comment]
@EdHarry that would be great! I am certainly still interested if the developers are okay with it.

**Comment by EdHarry** [comment]
@shannonekj ok, great, I just need to hear from @arangrhie if they're ok with a bioconda release and how they'd want to engineer all the callable scripts into a conda environment

**Comment by arangrhie** [comment]
Hi @EdHarry !! Thanks for offering a help! We will be happy if you could create a conda recipe for Merqury.
I am just not so sure what will be the best way to remove the environment variable.

>I'd recommend you just place / link all callable scripts into the bin directory of the conda environment
Can you do this when creating the conda environment?
I am not so sure what you mean. Certainly not a conda expert here.

**Comment by EdHarry** [comment]
@arangrhie is the environment variable MERQURY required for the scripts to run? I.e. is it referenced by any of the scripts? Or is it just a convenience for pointing at the installation location?

**Comment by arangrhie** [comment]
@EdHarry yes, all scripts are using `$MERQURY` as a path variable.

**Comment by EdHarry** [comment]
Bioconda recipe has been published, `conda install merqury`

**Comment by arangrhie** [comment]
Thanks, @EdHarry ! I've made a v1.1 release which contains a few bug fixes. Sorry for holding it for so long.

**Comment by EdHarry** [comment]
> Thanks, @EdHarry ! I've made a v1.1 release which contains a few bug fixes. Sorry for holding it for so long.

I've updated the recipe to 1.1 https://anaconda.org/bioconda/merqury
