### ISSUE TITLE
Phase_hapmers.blob

### ISSUE THREAD

**Issue by duhuipeng** [marbl/merqury#55]
Dear author

The phase diagram I draw using merqury is as follows:
![image](https://user-images.githubusercontent.com/58722433/125544075-532c4d3e-978a-4398-9940-1a84a4678027.png)

![image](https://user-images.githubusercontent.com/58722433/125543977-e8bba68b-70a1-4748-a16e-4737c8f647d7.png)
This is a  phase diagram of my two different individuals
But I found some problems at the head end (near 0), and I now want to take a separate look at the contig in these areas,I wonder what kind of text file there can know the contig corresponding to the area?
Best

**Comment by arangrhie** [comment]
Hello @duhuipeng ,

As from this thread: https://github.com/marbl/merqury/issues/53
>It's easy to calculate that from *.hapmers.count.
>Each columns are:
>```<fasta> <scaffold/contig> <hap1> <hap2> <total>```

This is the input file for this plot. <hap1> and <hap2> values are the numbers used for the X and Y coordinates.
The circle size is roughly telling you the k-mer (size) you want, which is the `<total>`.
