### ISSUE TITLE
Need to add path to /util folder ?

### ISSUE THREAD

**Issue by aureliendejode** [marbl/merqury#56]
Hello,

I am running merqury on a cluster and for now I made my own installation.
I have both merqury and meryl/bin in my PATH, but when I run the following command, I get an error message saying that the program cannot find the "/util/util.sh" script.

command: 
merqury.sh whole_illumina.meryl /proj/snic2020-6-155/canu_new_pacbio_all_third_lib-6-155/purge_dup/canu_purged.fa merqury_canu_purged

Do I need to add this "util" folder to the PATH or is there something wrong in my installation ?

Thanks

**Comment by brianwalenz** [comment]
You need to set the shell environment variable MERQURY to the directory that util/ is in.

**Comment by aureliendejode** [comment]
Hi,

Thanks! I mixed command lines from Merqury and meryl installations!
It is working now.
Cheers
