### ISSUE TITLE
asm.st.png vs asm.fl.png plot

### ISSUE THREAD

**Issue by B10inform** [marbl/merqury#59]
Hi,

What are the asm.st.png and asm.fl.png plot. The asm.st.png looks bit off, portion of the peak is out of the range.

Is it possible to get "CONTINUITY and PHASED" blocks for the haplotype resolved genome (diploid genome with two phased haplotypes)? 

**spectra-asm.st.png**
![image](https://user-images.githubusercontent.com/66449329/134572867-1e427495-aa83-4ed6-a980-674c05e562cf.png)

**spectra-asm.fl.png**
![image](https://user-images.githubusercontent.com/66449329/134572906-98a1ffe7-4f82-4602-8b22-804cee3d4eca.png)

**This is spectra-cn.st.png**
![image](https://user-images.githubusercontent.com/66449329/134573026-7c46d202-6bdb-4d25-b49c-906f45bd4351.png)

**hap1-spectra-cn.st.png (hap2 looks same)**
![image](https://user-images.githubusercontent.com/66449329/134573133-c7203df5-0118-4b13-8847-e45bad1c4732.png)

Thank you

**Comment by arangrhie** [comment]
Helo @B10inform ,

The *.st.png are stacked, filled version of the histograms, while *.fl.png contain unstacked, filled histograms.
The *.ln.png contains the line version only, identical to *.fl.png, without the filled color.

**Comment by B10inform** [comment]
Hi arangrhie,

Thanks for the information. In the spectra-asm.fl.png the share region (green) is smaller than the hap1 and hap2. Is this normal?
![image](https://user-images.githubusercontent.com/66449329/135157831-9ca494fd-0b46-40db-8da9-7ab94e02b1fa.png)

**I was also wondering if it was possible to get "CONTINUITY and PHASED" blocks for the haplotype resolved genome (diploid genome with two phased haplotypes) like below?**
![image](https://user-images.githubusercontent.com/66449329/135158105-1e4d17fd-822e-4272-9d16-0502aff6fb5d.png)

Thanks

**Comment by arangrhie** [comment]
Yes, it is possible to have shared peak smaller than the hap1 hap2 peak. This happens if the genome contains very diverse haplotypes.

For obtaining phase block related statistics and plots, you'd want to run Merqury in trio mode with haplotype specific kmers (hapmers). More details are laid out here: https://github.com/marbl/merqury/wiki#3-phasing-assessment-with-hap-mers-details

**Comment by arangrhie** [comment]
Hi @B10inform ,

The hapmers were created using the original parental assemblies from the [FALCON-Unzip](https://www.nature.com/articles/nmeth.4035) paper. No read data were available.

COL.fasta and CVI.fasta were generated with [TrioCanu](https://www.nature.com/articles/nbt.4277).

Arang
