### ISSUE TITLE
completeness file is empty

### ISSUE THREAD

**Issue by cell-c** [marbl/merqury#64]
Hi
Thanks for the good evaluation tool for genome assembly .

When I run merqury, it gave rise to error "Error: Unable to access jarfile /eval/kmerHistToPloidyDepth.jar" in spectra-cn.log.
All results work well except that kmer completeness file is empty.

What do you think the issue could be?

Thank you,

Chuang

**Comment by brianwalenz** [comment]
Looks like the MERQURY environment variable isn't set.  See step two in https://github.com/marbl/merqury#direct-installation.  This should be the location of the merqury install; `ls -l $MERQURY/eval/kmerHistToPloidyDepth.jar` should show the file.

**Comment by cell-c** [comment]
Many thanks  for your suggestion.
I resolved it. I checked files and found that $MERQURY was not set in a shell file.
