### ISSUE TITLE
Multiple reads datasets as meryl input

### ISSUE THREAD

**Issue by Overcraft90** [marbl/merqury#73]
Hi there,

I have a quick question. I'm now working on a HPC cluster and mainly using Bash scripts to launch jobs. Although unlikely, I still want to know for sure whether **meryl** can accept multiple reads datasets as input in a command as such:

`meryl k=21 count output $d.meryl ERR*`, or

it must be done a _union-sum_ afterwards in order to get a full meryl.db. 
Thanks in advance.

**Comment by brianwalenz** [comment]
Meryl will accept any number of input files.  You can mix FASTA and FASTQ files too.  Heck, you can mix FASTA and FASTQ records in the same file.
