### ISSUE TITLE
bining Hi-C reads

### ISSUE THREAD

**Issue by zhoudreames** [marbl/merqury#74]
in your https://github.com/marbl/merqury/blob/master/trio/exclude_reads.sh， we used father or mother unique kmer to bin the child's reads, how to build the pat.meryl or mat.mery ?  and whether the kmer database  is required to filter ？ 
meryl-lookup -memory 2 -exclude -mers pat.meryl -sequence $read1 sequence2 $read2 -r2 mat.R2.fastq.gz | pigz -c > mat.R1.fastq.gz

**Comment by arangrhie** [comment]
The pat.meryl and mat.meryl are the pat.hapmer.meryl and mat.hapmer.meryl, generated with `hapmers.sh`.
