### ISSUE TITLE
ccs.bam, fasta assemblies and meryl dataset

### ISSUE THREAD

**Issue by Overcraft90** [marbl/merqury#76]
Hi I have a quick question,

Unfortunately, I'm dealing with some _**ccs.bam**_ files for which it is not trivial to get back to the _**fastq**_ counterpart...; however, on S3 they have been made available also the diploid assemblies for this human individual.

So, my question is what would be in this case the best way to go in  order to build the `db meryl`? In fact, one way would be to convert _**bam**_ to _**fastq**_ (which is causing me some troubles), on the other hand for the same individual are also available CLR data for which they have been made available _**fastq**_ files. Would it be correct to use CLR to build the `db meryl` when I then use assemblies (both maternal and paternal) obtained form HiFi data?

Thanks in advance.

**Comment by skoren** [comment]
You cannot use CLR reads for merqury evaluations, their k-mer distributions are dominated by errors.

Luckily, you can can convert a bam file to fasta or fastq with samtools and awk:
```
samtools view reads.ccs.bam |awk '{RQ=-1; for (i = NF; i > 11; i--) { if (match($i, "rq:")) RQ=substr($i, 6, length($i)); } if (RQ >= 0.99) { print "@"$1; print $10; print "+"; print $11; }}'  > reads.ccs.fastq
```
or
```
samtools view reads.ccs.bam  |awk '{RQ=-1; for (i = NF; i > 11; i--) { if (match($i, "rq:")) RQ=substr($i, 6, length($i)); } if (RQ >= 0.99) { print ">"$1; print $10; }}' |fold -c > reads.ccs.fasta
```

This will confirm the read is Q20 (RQ >= 0.99) and dump its sequence.

**Comment by Overcraft90** [comment]
Hi @skoren,

Thank you so much! I will try and let you know.

**Comment by Overcraft90** [comment]
Thank you so much,

I have been able to retrieve HiFi reads from my noisy CLR data. Thanks a lot for sharing these two short script! I think we can close the issue.
