### ISSUE TITLE
HG002.k21.meryl.tar and  NA12878.k21.meryl.tar are missing 

### ISSUE THREAD

**Issue by cchd0001** [marbl/merqury#8]
Hi ,

I am downloading data of HG002 and NA12878 from [here](https://obj.umiacs.umd.edu/marbl_publications/merqury/index.html) but the HG002.k21.meryl.tar and NA12878.k21.meryl.tar links failed before my downloads were finished. Is there any other available links to download them?

Best wishes 
Lidong Guo

**Comment by arangrhie** [comment]
Hi @cchd0001 , thanks for reaching us out.
Apologies for the inconvenience.
The server we hosted the data seems like is having some issues at the moment.
Will let you know when the data is available.

In the mean time, the meryl dbs for HG002 and the parental genomes are available 
here: https://s3-us-west-2.amazonaws.com/human-pangenomics/index.html?prefix=HPRC/HG002_Assessment/merqury/.

Best,
Arang

**Comment by cchd0001** [comment]
Hi Arang，

Thanks a lot.  The new link works fine for me.

Best wishes
Lidong Guo

**Comment by arangrhie** [comment]
Hi Lidong,

The download page (https://obj.umiacs.umd.edu/marbl_publications/merqury/index.html) is fixed!
Hope you found all needed.

Thanks,
Arang
