### ISSUE TITLE
K-mer comparison density plot

### ISSUE THREAD

**Issue by dirkjanvw** [marbl/merqury#80]
Hi, thanks for providing an amazing tool! It works exactly as I expected!

I especially see the benefits of using merqury over KAT with regard to speed. However, with KAT, I am able to create density plots of the comparisons of two sets of k-mers (`kat plot density`). I know that this does not make sense when calculating the completeness of a genome assembly, but I was wondering: is it possible to use merqury (or meryl?) to create these density plots for a comparison of two meryl databases?

**Comment by arangrhie** [comment]
Hello @dirkjanvw,

You could try using https://github.com/marbl/merqury/blob/master/plot/to_hist_for_plotting.sh for your meryl dbs.
This generates one histogram file that could be fed into the [plot_spectra_cn.R](https://github.com/marbl/merqury/blob/master/plot/plot_spectra_cn.R). The color code wouldn't be that fancy and follows the ones used in Merqury, but you would be able to plot whatever meryl db has in it and compare.
```
Rscript $MERQURY/plot/plot_spectra_cn.R --help
```
has the detailed options you can adjust for plotting.

**Comment by dirkjanvw** [comment]
Thanks a lot for the reply! I haven't manage to create 2d density plots, but the spectra-cn plots are actually way more useful for my purposes of comparing sequencing libraries. The scripts work perfectly!
