### ISSUE TITLE
NG block

### ISSUE THREAD

**Issue by duhuipeng** [marbl/merqury#81]
dear author
Now I want to draw this plot separately
![image](https://user-images.githubusercontent.com/58722433/187344449-7243a7af-9bef-4e24-b011-3ed4064d6999.png)
My input file format is as follows，but it appear error
![image](https://user-images.githubusercontent.com/58722433/187344696-73250e90-942b-4450-ae4a-2ae228401927.png)
Could you please provide the input file format
Best

**Comment by arangrhie** [comment]
Hello, it should be the `-b ....phased_block.sizes`. See more details with
```
Rscript $MERQURY/plot/plot_block_N.R --help
```
For example:
```
block   mat.hapmer      6635314
block   mat.hapmer      6213435
block   mat.hapmer      5738677
block   mat.hapmer      5696453
block   mat.hapmer      5627365
block   mat.hapmer      5209980
```
The blocks are colored by col2; so extract the lines that matches what you want on col2. Not sure what you intend to measure though..? The blocks are identified on one assembly, so pulling only one type of block wouldn't make much sense on the N* scale.

**Comment by duhuipeng** [comment]
thanks , got it
