### ISSUE TITLE
meryl-lookup - where is the script?

### ISSUE THREAD

**Issue by LandiMi2** [marbl/merqury#88]
Hey , I am trying to create hap blobs for my hap1 and hap2 assembly. But I don't seem to find the `meryl-lookup` script. I use `find` command, and I don't see this script in this repo. Do I have to install it separately?

**Comment by arangrhie** [comment]
Hello @LandiMi2 ,

meryl-lookup is part of [meryl](https://github.com/marbl/meryl/tree/master/src/meryl-lookup).
There should be no need to do an additional installation of it!

**Comment by LandiMi2** [comment]
Thanks, @arangrhie. I had installed Meryl using conda, and `meryl-lookup` was not found. Anyway I got it now in the src you sent.
