### ISSUE TITLE
R ERROR

### ISSUE THREAD

**Issue by woodoo46** [marbl/merqury#89]
Hi,

I tried to run merqury pipeline, and at the end of the log file, I had this error message:

[1] "x_max: "
[1] "y_max: 348694.5"
[1] "## Line graph"
Error in if (all(is.finite(continuous_range_coord)) && diff(continuous_range_coord) <  :
  missing value where TRUE/FALSE needed
Calls: spectra_cn_plot ... expand_limits_continuous -> expand_limits_continuous_trans
In addition: Warning message:
In max(dat[dat[, 1] != "read-total" & dat[, 1] != "read-only" &  :
  no non-missing arguments to max; returning -Inf
Execution halted

I am running pacbio hifi reads on pacbio hifi reads assembly (same data set). Or I did the wrong way?

Thanks.

George

**Comment by arangrhie** [comment]
Hi George,

Seems like an error occurred upstream. Could you check the log file?

Thanks,
Arang

**Comment by arangrhie** [comment]
Closing this for now. Feel free to re-open, @woodoo46
