### ISSUE TITLE
completeness.stats column explanation

### ISSUE THREAD

**Issue by mictadlo** [marbl/merqury#93]
Hi,
I just wonder what the values mean in the `completeness.stats` file.

```
> cat *.stats
Nbgenome all 1496088069 1538347195 97.253
```
Thank you in advance,

Best wishes,

Michal

**Comment by arangrhie** [comment]
Please refer this [Wiki](https://github.com/marbl/merqury/wiki/2.-Overall-k-mer-evaluation#3-k-mer-completeness-recovery-rate).
