### ISSUE TITLE
Segmentation Fault at meryl-lookup

### ISSUE THREAD

**Issue by kneubehl** [marbl/merqury#96]
Hi,
I am getting a segmentation fault error at the meryl-lookup stage. I have tried through the manual installation route (made very sure to install the specific meryl requested) and the conda route and both are giving me the same issue. The .spectra-cn.log file (attached) also seems to be incomplete compared to when I have the same version of Merqury in the past (installed this on a new workstation). Any guidance would be appreciated.
[bfqtaro_merq.spectra-cn.log](https://github.com/marbl/merqury/files/10703743/bfqtaro_merq.spectra-cn.log)

**Comment by arangrhie** [comment]
Hi @kneubehl,

Sorry for the hassle..! Please use the meryl v1.4 release and the latest Merqury on this github.
I'll update the README doc.

**Comment by kneubehl** [comment]
No worries. Easy fix. Works fine now. Thanks!
